### ISSUE TITLE
Array out of bounds exception, Block.java

### ISSUE THREAD

**Issue by Raotor123** [Anuken/Mindustry#10]
Occurs when I place a router/tunnel on a full conveyer belt.
![image](https://user-images.githubusercontent.com/25741824/33847783-012f9e94-deac-11e7-8ee5-2d29fc6aea3f.png)

**Comment by Anuken** [comment]
Moving the conversation here, it looks like an overflow. Not sure what's causing it, but I added a few small safeguards in there to make sure it doesn't happen again. As for the tunnels, that _was_ intentional initially, but not particularly good design on my part. I've changed it, and fixed the router tunnel bug as well.

**Comment by Raotor123** [comment]
Good work! Nice to see you so active.
