### ISSUE TITLE
Help on mode on GUI

### ISSUE THREAD

**Issue by rangzen** [Anuken/Mindustry#100]
Hello,
I had to see:
```
	waves,
	sandbox{
		{
			infiniteResources = true;
			disableWaveTimer = true;
		}
	},
    freebuild{
        {
            disableWaveTimer = true;
        }
```
in the code to understand the different mode.
Is it simple to add a popup on mouseover or on selection?
I'm starting with LibGDX, maybe can you give me some hint to see if I can implement it myself ?
Anyway thank you very much for your game !

**Comment by Anuken** [comment]
Since Android can't have 'mouse overs' and a popup would probably be too intrusive, I would probably create a info button next to the mode selection menu, which would show a FloatingDialog explaining how each mode works.

If you want to try implementing this yourself, see how the dialogs and their content/text are structured in the `dialogs` package, then add the dialog to `UI` and show it when the info button is pressed.
