### ISSUE TITLE
Drones Issue

### ISSUE THREAD

**Issue by good777LUCKY** [Anuken/Mindustry#1008]
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *99*

**Issue**: *Sometimes enemy flying drone overlaps with spirit drone, so it can't change the other path and keeps spinning around. (Top left corner of the video.) Of course, I can just kill enemy drone, but can you change drone AI a bit?
[I'm not talking about the phantom drones that are spinning around me.]*

**Steps to reproduce**: *It usually happen when your spirit drone is not working yet and enemy drone overlap with spirit drone.*

**Video link (GIF)**: *https://ibb.co/5L6nDg0*

**Comment by good777LUCKY** [comment]
is this not bug?

**Comment by TsjipTsjip** [comment]
Cannot reproduce this. Release build 100.1

I seem to have a hard time understanding what exactly is happening on your end versus what is supposed to happen. If an enemy drone overlaps with one of yours (which I could not reproduce in any way due to the enemy drone diverting to attack either the spirit drone or the structures) you can just kill it or have a Scatter Turret nearby to kill it.
May have been a bug before fixed over the release discrepancy between 99 and 100.1

**Comment by Anuken** [comment]
Either way, this isn't really a bug.
