### ISSUE TITLE
ALL SECTORS have been reset to wave 0 and under attack, item count reset to 0, tech tree reset.  All buildings are normal.

### ISSUE THREAD

**Issue by egfthomas** [Anuken/Mindustry#10169]
### Platforms

Linux

### Build

steam build 146

### Issue

Save file became semi-corrupted in Steam - I say "semi-corrupted" because ALL sectors are under attack and the tech tree has been 100% reset.  Even non-vulnerable sectors like salt flats and ground zero are reset back to wave 1.  All buildings are fine on all sectors.  Is there some console command I can do to say "make all sectors captured" except the vulnerable ones ?  If we could do that I think it would be fine and I'll just re-do all the tech tree.  Without recapturing all captured sectors (my item count is 0 on every map) I won't be able to play this save anymore, although it would be quite a challenge (I might play it anyway)

![image](https://github.com/user-attachments/assets/7dc4f292-5d75-4336-8a9c-87b72f9836c9)

### Steps to reproduce

Nothing, just normal steam saving between two different linux machines

### Mods used

none

### Save file

Game hangs on export data screen saying "Zenity is not responding" so I can't export a save at this point.  If you know how to export another way, please let me know

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by broganeuquoixe** [comment]
it's normal for the game to hang on when exporting a save since it's done on the same thread as the main game and all resources get allocated to exporting the save instead of "running the game" leading to your computer thinking the game is crashing.
Just let it run. Otherwise another way to do it is just going into settings > game data > open data folder and then zipping and sending the saves folder, last_log.txt and settings.bin. A normal export includes other stuff but for this issue I think these are the only ones relevant

**Comment by egfthomas** [comment]
OK it hangs at the title screen too when exporting.  I'll zip the data files

**Comment by egfthomas** [comment]
It's 44MB, too big to post on github

**Comment by broganeuquoixe** [comment]
https://github.com/timvisee/send-instances/

**Comment by egfthomas** [comment]
https://send.monks.tools/download/3d4752006558dedf/#EpVs0NdokkZTDV2R4csWQQ

**Comment by broganeuquoixe** [comment]
Here you go buddy, sorry for the wait. I've tried to repair what I could. Replace this with your current "saves" folder and it should be good to go. Then please close this issue.

https://send.vis.ee/download/8b7b27753f21b230/#EWRzbbN6lh31fzLuM1CtKA

and here's the settings.bin file, replace this one too, you just need to change the fullscreen and ui scale settings since I changed them
[settings.zip](https://github.com/user-attachments/files/16829794/settings.zip)

**Comment by egfthomas** [comment]
Thank you, much appreciated!

**Comment by egfthomas** [comment]
s
