### ISSUE TITLE
conductPower on payload unloader, but not on payload loader

### ISSUE THREAD

**Issue by HightAngst** [Anuken/Mindustry#10223]
### Platforms

Windows

### Build

steam 146

### Issue

Payload loader does not conduct power.
![image](https://github.com/user-attachments/assets/6770aa8b-29bc-46de-9411-20600035fe73)

### Steps to reproduce

Place payload loader next to mass driver
Connect power only to payload loader 

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by HightAngst** [comment]
Same thing, if you only connect power to mass driver
![image](https://github.com/user-attachments/assets/318b4af4-e8f9-42c0-97fe-286ae58f43a3)

**Comment by Anuken** [comment]
The payload loader doesn't need to conduct power as it does not output it.

**Comment by mprahlkamps** [comment]
I don't understand why this issue is closed? Seems like a bug to me if one building transfers power to the neighboring buildings and the other does not.

I don't know what the desired behaviour is but in my opinion the loader and the unloader should behave the same. 

Additionally its not like the loader itself is powered.

<img width="724" height="874" alt="Image" src="https://github.com/user-attachments/assets/b76b3893-7ae2-4320-a8bd-ea2e504e995a" />

**Comment by Anuken** [comment]
The unloader can output power, like a battery can, because it can unload batteries and transfer them to nearby blocks.

The loader is the same as any other power-consuming block - it doesn't conduct power.
