### ISSUE TITLE
Cannot install java mods on Android

### ISSUE THREAD

**Issue by SanekGamer007** [Anuken/Mindustry#10275]
### Platforms

Android

### Build

be 25394

### Issue

Cannot install any java mod using any method (import from file, github and mod browser all dont work)
Android 14
heres screenshot
![Screenshot_20241018-150740_Mindustry BE](https://github.com/user-attachments/assets/618b0396-ceab-4740-ab3b-9fc9d7975188)
worth to mention that logs dont contain anything useful.

### Steps to reproduce

Import/Download any java mod.

### Mods used

None

### Save file

[save.zip](https://github.com/user-attachments/files/17436491/save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Matita008** [comment]
**always** add the logs

**Comment by SanekGamer007** [comment]
> **always** add the logs

okie dokie -
[last_log.txt](https://github.com/user-attachments/files/17439735/last_log.txt)

**Comment by SanekGamer007** [comment]
i also have matlog so i can send logs from there if needed (not sure if it contains sensitive information though)

**Comment by Anuken** [comment]
This is a new "security feature" for Android. Mindustry already tries to work around it, but that seems to be failing on your device. The workaround *is* functional on my device. There's nothing I can do about it.

**Comment by SanekGamer007** [comment]
is it maybe possible to allow the app to use shizuku or root as fallback in case this workaround fails?

**Comment by Anuken** [comment]
I have no idea what those are or how they would help.

> well atleast latest stable works fine...

Because it targets an older SDK, so the security measures don't apply. I cannot continue to use the older SDK target as it makes the app ineligible for app stores (and in the far future, installation).

**Comment by alexytomi** [comment]
> I have no idea what those are or how they would help. They do not sound like something an average user would have access to.
> 
> > well atleast latest stable works fine...
> 
> Because it targets an older SDK, so the security measures don't apply. I cannot continue to use the older SDK target as it makes the app ineligible for app stores (and in the far future, installation).

Shizuku is essentially an API apps can call to get adb permissions. 

Root is literally just root permissions like in normal linux distros.

Using shizuku as a fallback is likely to be *very broken* because for some phones, the command to "switch user" for the appropriate file permissions to work does so strangely and screws up the file permissions of the app, in some cases not allowing the app access to its own data and resources.

Anyone with experience using shizuku and terminal emulators like termux should already be able to grant mindustry proper permissions in that directory anyway, the "fix" being asked is too niche and for that niche, is redundant.

A game that asks for root permission is also extremely suspicious at first glance.

**Comment by SanekGamer007** [comment]
my "fix" was just the first thing that came to my mind
also totally agree with alexytomi

**Comment by byzp** [comment]
This issue occurs when I use an external file manager to import mods. Since Mindustry is not the file owner, it cannot modify the read/write permissions. Manually changing the file attributes to read-only might resolve this problem

**Comment by Anuken** [comment]
>  Since Mindustry is not the file owner, it cannot modify the read/write permissions. 

But the file permissions are only changed once the file is imported into the game data folder. That shouldn't be an issue.

**Comment by byzp** [comment]
> > Since Mindustry is not the file owner, it cannot modify the read/write permissions.
> 
> But the file permissions are only changed once the file is imported into the game data folder. That shouldn't be an issue.

The mod is directly copied into the mod folder by an external file manager, with Mindustry not being involved at all. Due to the new storage mechanism introduced in Android 11, even though the file is located at /storage/emulated/0/Android/data/io.anuke.mindustry/mods, it does not belong to Mindustry, and therefore its read/write permissions cannot be changed by the game.

**Comment by SanekGamer007** [comment]
> > > Since Mindustry is not the file owner, it cannot modify the read/write permissions.
> > 
> > 
> > But the file permissions are only changed once the file is imported into the game data folder. That shouldn't be an issue.
> 
> The mod is directly copied into the mod folder by an external file manager, with Mindustry not being involved at all. Due to the new storage mechanism introduced in Android 11, even though the file is located at /storage/emulated/0/Android/data/io.anuke.mindustry/mods, it does not belong to Mindustry, and therefore its read/write permissions cannot be changed by the game.

i wonder if storing mods at /data/data instead would help

**Comment by Anuken** [comment]
> The mod is directly copied into the mod folder by an external file manager

**if** you're copying the file there manually (and I imagine 99% of people don't even know how to do that), it makes sense. If you use *any* in-game method of importing the mod, it does not. Either way, this is an edge case - you should be using the in-game "import mod" button.

> i wonder if storing mods at /data/data instead would help

There's a reason data isn't stored there anymore; it is inaccessible to users, which makes it difficult to view data or retrieve logs.

**Comment by alexytomi** [comment]
> This issue occurs when I use an external file manager to import mods. Since Mindustry is not the file owner, it cannot modify the read/write permissions. Manually changing the file attributes to read-only might resolve this problem

This is a ROM specific issue, some have it, some don't. Using the AOSP app to access the Android/data folder is bound to cause permission issues as it is not supported by Android itself, you are supposed to use [SAF](https://developer.android.com/guide/topics/providers/document-provider).

**Comment by alexytomi** [comment]
I've now figured out why this is likely also breaking your github imports and mod browser, the permission on the mods folder itself is screwed.

Doing any operation on the folder itself through the app's code should resolve the issue (that's more of a hack than an actual fix though) or using adb then `chown`'ing it, this requires the app be debuggable, otherwise you will need to clear data to reset the permission shenanigrins

What should be done instead is allow accessing mod files via SAF similar to apps like Termux. This is the intended way of messing with anything in the Android/data directory.

Anyone using the Android/data bypass through AOSP files app elevated permissions simply just can't be supported. 

Now I do wonder whether a PR for allowing SAF access to Mindustry's Android/data folder would be welcome? Would be happy to add do it myself
