### ISSUE TITLE
Playback device doesn't automatically switch (Windows)

### ISSUE THREAD

**Issue by DarkEyeDragon** [Anuken/Mindustry#1147]
**Platform**: *Windows*

**Build**: *100.1*

**Issue**: When switching audio devices (eg. speakers to headset) in the windows playback settings the audio should swap to that device automatically.

**Steps to reproduce**: Plug in any audio device (and switch to it using the windows audio/sound manager)

**Comment by Anuken** [comment]
As far as I know, this requires accessing Windows API, which I will not be implementing.

**Comment by admin-ll55** [comment]
Okay

**Comment by NA0341** [comment]
Hi Anuken!
Do you use the [Java Media Framework (JMF)](https://www.oracle.com/java/technologies/javase/java-media-framework.html)?
I asked a friend about this topic because changing sound output at runtime is an issue in many Java® - applications (like [minecraft](https://bugs.mojang.com/browse/MC-25528)). He told me that a Java programm doesn't need to use any Windows-related API - because that's just what independency means… …I [found an article](https://docs.oracle.com/javase/tutorial/sound/accessing.html) relating to that topic.

I really hope that can help you with development of mindustry :)
Thank you for your time and this awesome game!
-na0341

**Comment by Anuken** [comment]
> Do you use the Java Media Framework (JMF)?

No, I use OpenAL, as does Minecraft.
