### ISSUE TITLE
Mindustry requests "Input Monitoring" but works even if it is denied.

### ISSUE THREAD

**Issue by schumannd** [Anuken/Mindustry#1219]
**Platform**: macOS Catalina 10.15.1 

**Build**: 4.0 Build 96

**Issue**: While investigating some malicious software, I found that Mindustry had also requested (and been denied) the permission to "monitor input from your keyboard even while using other apps". This can be checked under System Preferences -> Security & Privacy -> Input Monitoring. It was working fine, so I guess requesting these permissions is not necessary.

**Steps to reproduce**: should happen when downloading and running mindustry on MacOS Catalina.

I would be very interested in knowing why this happens, how this can be avoided and what permissions should be requested instead. I was looking for keyloggers, and found Mindustry :) Any input very welcome.

**Comment by Anuken** [comment]
I am not requesting input monitoring of any specific sort with Mindustry; only the standard SDL text and keyboard input functions are used. Looking it up, this seems [like it could be a bug with MacOS](https://github.com/wesnoth/wesnoth/issues/4109) - either way, since this isn't causing any game issues issues, I don't think it matters.
