### ISSUE TITLE
From ECS to OOP

### ISSUE THREAD

**Issue by RUSshy** [Anuken/Mindustry#128]
Hi,

This is not an issue but more a question

In previous game "Koru" you used ECS, but in your new games you use traditional OOP

Why ? is ECS bad ? 

Im learning and i trying to learn ECS but i dont know if it is really usefull

Ty!

**Comment by Anuken** [comment]
Most of my new games use OOP because I made them in game jams and had limited time. OOP is generally faster to develop with initially, but gets messy in large projects.

One of the reasons I'm not using ECS in Mindustry is because that's how it initially started out due to time constraints.

Would I use ECS in Mindustry if I could do it without rewriting a lot of code? Maybe. I'm not happy with the current OOP system, since it's leading to rigid entity structure, but at the same time, ECS can be a chore to use. It's probably less performant too, although I haven't tested much. 
In my experience, ECS seems to make designing specific entities very difficult, and creates more problems than it solves. I don't claim to be an expert on this at all-- there are plenty of people who swear by ECS, and it's quite possible that I just haven't been using it properly, or that my projects weren't big enough to see the benefits of ECS. 

Despite all this, I would say it's definitely worth learning ECS. Try it out for yourself, and see what you think.
