### ISSUE TITLE
HDMI audio output isn't restored after switching between KVM

### ISSUE THREAD

**Issue by admin-ll55** [Anuken/Mindustry#1369]
**Platform**: Windows

**Build**: 102.2

**Issue**: it is quite uncommon that the audio signal is gone after switching between KVM. the model of KVM i use is from ATEN. i can confirm the audio is restored in almost any applications successfully after switching except this specific game.

**Steps to reproduce**:
1. switch to kvm port 1, start the game
![image](https://user-images.githubusercontent.com/36874774/72240861-47391c80-3620-11ea-9ea7-5fc62eadd13b.png)

2. switch to kvm port 2, play some audio
3. switch to kvm port 1, only the game is missing its audio
![image](https://user-images.githubusercontent.com/36874774/72240981-8b2c2180-3620-11ea-8e49-cdc693b5fbd2.png)

**Comment by Anuken** [comment]
Duplicate report; I won't be fixing this.

**Comment by funlennysub** [comment]
Sorry for the bump but since this bug been bothering me, I decided to make a mod that fixes it. All it takes is 3 lines of code and can be implemented in game with a button in sound settings menu. (this one seems like the best-looking option if you don't want to keep track of when the audio dies etc) If you want, I can make a pr later
![image](https://github.com/user-attachments/assets/65626fd9-7ea7-435b-b051-44d28008f25f)
