### ISSUE TITLE
AI Targeting

### ISSUE THREAD

**Issue by CaribbeanMax** [Anuken/Mindustry#1372]
**Platform**: *Mac*

**Build**: *Steam 102.3*

**Issue**: *Target priorization is even more messed up now.*
Even without blocks from different priority groups in range, the AI will now almost always aim at the last block scanned by `findTile` in `BlockIndexer.java`.

![AItargeting](https://user-images.githubusercontent.com/23070598/72253503-fadee400-3601-11ea-9d8b-8bd04d01a2e6.png)

**Steps to reproduce**: *See picture.*

**Suggestion**:
I am not going to make a PR for this myself because i can't test the change right now.
*build 101 original in `findTile BlockIndexer.java`:*

```
if(ndst < range && (closest == null || ndst < dst || (usePriority && closest.block.priority.ordinal() < e.block.priority.ordinal()))){
    dst = ndst;
    closest = e;
}
```

*what i did propose as a fix via discord back then:*

```
if(ndst < range && (closest == null || (ndst < dst && (!usePriority || closest.block.priority.ordinal() <= e.block.priority.ordinal())))){
    dst = ndst;
    closest = e;
}
```

*what got changed from v101 to 102 instead:*

```
if(ndst < range && (closest == null || ndst < dst || (usePriority && closest.block.priority.ordinal() <= e.block.priority.ordinal()))){
    dst = ndst;
    closest = e;
}
```
So just the "<" -> "<=" happened and none of the other minor tweaks to the logic.

**Comment by Anuken** [comment]
I've taken a proper look at this now (without blindly changing things), and your solution isn't completely correct either. The targeting needs to prefer blocks with higher priority, even if they are further away.

Incorrect *(wall is found first, and since the `ndst < dst` condition is not met for the turret, it is not targeted)*
![image](https://user-images.githubusercontent.com/10100000/72259532-baba3a00-35de-11ea-8232-d4ffb8e1db6b.png)

Correct *(turret priority is checked against wall, and picked due to higher priority)*
![image](https://user-images.githubusercontent.com/10100000/72259604-e5a48e00-35de-11ea-93fd-c54677d7cce3.png)
