### ISSUE TITLE
[forking] adding custom emojis

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#1458]
**Platform**: `mac`

**Build**: `v103`

**Issue**: currently updating my crater branch, and i really wanted to add an emoji, but it appears its only straightforward to add those for blocks/items/liquids, so i kinda [hacked it in](https://github.com/Anuken/Mindustry/pull/1260/commits/883a2a9b59a9c82c55c33c662753b70c09e54616), any thoughts?

**Steps to reproduce**: really wanting to add a relevant emoji to my pull/fork.

**Comment by Quezler** [comment]
also, on a related note, what is the reasoning behind mechs/units not having an emoji counterpart?

**Comment by Anuken** [comment]
Emoji generation is automatic; adding them manually may or may not work properly. The system isn't designed for custom emojis.

Units and mechs don't have custom emojis, because:
1. They may not have sprites on the UI texture atlas, which causes a lot of extra texture binding
2. They will be completely reworked  in 6.0, and I don't want to waste my time

**Comment by Quezler** [comment]
noted 👍
