### ISSUE TITLE
Keyboard Player Movement (Android)

### ISSUE THREAD

**Issue by BenKey0** [Anuken/Mindustry#1465]
**Platform**: *Android*

**Build**: *Release Build 102.3.*

**Issue**: *I am unable to move the player (Ship) using the keyboard. All key binds seems to be set correctly and other keys on the keyboard function normal such as the arrow keys to navigate the Build menu. .*

**Steps to reproduce**: 
- Start Mindustry with USB OTG adapter (Keyboard and mouse plugged in) 
- It should be noted the keyboard and mouse works in other apps and the Android interface itself.
- Start a new map/load existing (Bug persistent everywhere).
- Enable Keyboard and mouse support in Settings.
- Attempt to move Player using "WASD" Notice player does not move.

**Comment by QmelZ** [comment]
May be a hardware/software problem, works fine for me. I suggest reinstalling the game, if still not fixed, try the itch.io apk

**Comment by Anuken** [comment]
This works correctly on my (*Android 7*) phone with a real keyboard. Keyboard input on a simulator (*Android 10*) seems completely broken, but it's not clear whether the cause is the simulator itself (*which is probable*) or something wrong with the input code. It seems to spam up and down key events repeatedly when the button is held. These events are *not* key repeat events and are all identical (*except for the timestamps, of course*). 

I don't know if the same thing happens on a real phone, and I can't find anything similar online. Unless someone else with a more recent device wants to look into this, it won't be fixed.

**Comment by DillonHHH** [comment]
For anyone else looking into this problem, I've just solved it by switching keyboards. I was using Microsoft Swiftkey, and noticed the on-screen keyboard would pop up every time I typed, despite having a setting to not do that. After switching keyboards, that issue no longer occurs, and I can play Mindustry on mouse and keyboard just fine.
