### ISSUE TITLE
Restore E/R controls

### ISSUE THREAD

**Issue by franz-wexler** [Anuken/Mindustry#15]
From what I can see, in the newest beta 2, instead of using A/R to change direction of conveyors, we should use scroll wheel.

However, on laptops without mice, it is practically impossible to scroll precisely. As it is, I won't play beta 2 at all.

My suggestion would be to restore A/R controls. The player will be able to choose whether they prefer using keyboard or mouse and everyone should be happy.

**Comment by Luxray5474** [comment]
I agree, we should still be able to rebind the rotate functions to keys. Also, the zoom-lock function is weird, and should be switched around.

**Comment by franz-wexler** [comment]
BTW, your game is amazing, @Anuken. I really enjoyed playing it. It isn't as overcomplicated as Factorio and runs smoothly on my old hardware. 

If it wasn't written in Java I would certainly help you in developing it!

**Comment by franz-wexler** [comment]
And I don't think the zoom-lock function is weird. If you are talking about the fact that you need to hold Ctrl to zoom in/out, I find it very straightforward. It is standard in normal desktop applications.

**Comment by Anuken** [comment]
You have a good point; re-added in de6ccbbc8838c20097559f9b8f5b9f5d58c5648d. I was pushing 3.0 when you posted, so this should be available in the latest release.

@Luxray5474 Are you referring to the fact that zoom locks to specific levels? That's there in order to prevent ugly pixel artifacts. Currently, it locks to whole-number upscaling of the pixel framebuffer. If the screen had, say, 3.6x scaling, you would have half-scaled chunks of pixels everywhere.
