### ISSUE TITLE
Game crashes instantly

### ISSUE THREAD

**Issue by Exotic-Algorithms** [Anuken/Mindustry#1588]
Platform: windows 10

Issue: I bought the game off steam.  I hit play.  It says the game is running but then it just crashes. No windows open or anything.   Other people are having the same issue.  Check here https://steamcommunity.com/app/1127400/discussions/0/1628538707062836768/

**Comment by DeltaNedas** [comment]
works on my machine
try launching desktop.jar manually with `java -jar`
if you dont have java installed use java from the installation in steamapps/common/Mindustry

**Comment by Anuken** [comment]
Post the crash log.

**Comment by Exotic-Algorithms** [comment]
Where do I find the logs

**Comment by Anuken** [comment]
Check the local data folders in Steam (Right click -> properties -> local files -> browse local files) or %appdata% in start menu -> Mindustry.

**Comment by Anuken** [comment]
Closing due to lack of response, and the fact that I don't have anything new to say.
- If you have a file starting with `hs_err` in the game folder, your OS/drivers don't like something about OpenGL. I can't help you with that, as the problem isn't reproducible on my devices. Some people have said that reinstalling Windows helps, but I have no idea why or what causes it.
- If you have anything similar to it, read through the thread you linked and see if someone else had a problem like that with a response.
- If you don't have any log, there's nothing I can do.
