### ISSUE TITLE
iPhone X resolution not working

### ISSUE THREAD

**Issue by infinitedaremo** [Anuken/Mindustry#1647]
**Platform**: iOS

**Build**: Latest

**Issue**: iPhone X resolution not working despite screenshots showing support

**Steps to reproduce**: Play the game on iphoneX

**Comment by Anuken** [comment]
Mindustry doesn't support full resolution on phones with borders or notches; this is not a bug. I don't know which screenshots you're referring to, because the ones displaying UI on the App Store clearly show black bars on the sides:
![image](https://user-images.githubusercontent.com/10100000/75585673-a58b5480-5a40-11ea-9595-ddfc08fd6fc3.png)

**Comment by infinitedaremo** [comment]
![33370759-48C5-4A04-A8CB-DCA4744EED58](https://user-images.githubusercontent.com/61242984/75585855-f31cb700-5a6a-11ea-8b90-243bcd63f5da.png)

The screens look like it supports varying resolutions is all.

**Comment by DeltaNedas** [comment]
black bar > hole in screen hiding block list

**Comment by mRebornM** [comment]
Actually my phone has the same screen ratio as iphone x and mine supports fullscreen

**Comment by infinitedaremo** [comment]
Ahhh so it’s just the notched phones which don’t go full screen. Fair enough.
