### ISSUE TITLE
[mods] runtime generated item require a restart to work

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#1727]
**Platform**: GNU/Linux

**Build**: master from about a day ago

**Issue**: two issues so far:
1. The texture is a black square before mods are reloaded.
2. In my light-water-reactor block at least, the items cannot be used in crafters before a reload.

**Steps to reproduce**:
1. load [DeltaNedas/resources](https://github.com/DeltaNedas/resources) and [DeltaNedas/nuclear](https://github.com/DeltaNedas/nuclear)
2. look in core database / item source at the black squares (i found a white square once)
3. put second last item into light-water-reactor in power tab and see it not work
4. reload mods
5. repeat step 2 + 3 but the textures all exist and reactor works too

Before reload: 
item source
![item source](https://user-images.githubusercontent.com/39013340/76917068-4c357900-68ba-11ea-9dcd-a9c1d43a9cac.png)
dead reactor
![dead reactor](https://user-images.githubusercontent.com/39013340/76917097-61aaa300-68ba-11ea-9ac7-0b67ad5e3d37.png)

After reload:
item source
![item sourcce](https://user-images.githubusercontent.com/39013340/76917173-8d2d8d80-68ba-11ea-9544-450ba738e477.png)
working reactor :D
![working reactor](https://user-images.githubusercontent.com/39013340/76917194-9cacd680-68ba-11ea-88f0-91cf23a83cfe.png)

**Comment by DeltaNedas** [comment]
texture stuff is probably atlas being recreated and refreshed, but i have no idea why it breaks reactor

**Comment by Anuken** [comment]
The mods you posted have a lot of code to look through, and it's not clear how much of it is really relevant. I need a single script (preferably with a single item/block) that shows the issue occurring.

**Comment by DeltaNedas** [comment]
```js
const router = extendContent(Router, "new-router", {
	load() {
		const old = Core.atlas.getPixmap("router");
		const color = new Color();
		var x, y;
		const pixmap = new Pixmap(32, 32);

		// Make a new dark router and set to "new-router" in atlas
		for (x = 0; x < 32; x++) {
			for (y = 0; y < 32; y++) {
				color.set(old.getPixel(x, y));
				pixmap.draw(x, y, color.mul(0.75));
			}
		}

		// Set it in atlas, do not override it so that old router looks normal
		Core.atlas.addRegion(this.name, new TextureRegion(new Texture(pixmap)))
		this.super$load();
	}
});
router.buildVisibility = BuildVisibility.sandboxOnly;
router.localizedName = "New router!";
```

**Comment by Anuken** [comment]
I'm surprised that works at all. On my machine, it's an immediate segfault.

You're creating a texture, which requires an openGL context, which requires the main thread. `load()` does not get called on the main thread, so you get a black texture (or in my case, a JVM crash).

Replacing the region line with 
`Core.app.post(run(() => Core.atlas.addRegion(this.name, new TextureRegion(new Texture(pixmap)))));`

...solves the problem by making the texture get created on the main thread, but I would still not recommend adding anything to the main atlas manually. You're going to see horrible performance due to texture switching, and (potentially) all sorts of weird undefined behavior. This isn't something that the game is supposed to support.

If you're dynamically generating items/textures *based on multiple mods*, I would recommend making a script to generate the content/image files before distribution instead.
