### ISSUE TITLE
Underflow gates jamming unexpectedly

### ISSUE THREAD

**Issue by ghost** [Anuken/Mindustry#1736]
**Platform**: Windows

**Build**: 104.5 vanilla

**Issue**: Underflow gates when linked up to a full line on the side outputs do not send the item being transported,  out the opposite end of the input, taking 1 item from the full line on the sides fixes the issue and causes the underflow gate to function as normal.

**Steps to reproduce**: I was sorting out an error I had made in my sandbox world which had caused the conveyors to mix, the side lines were full due to it just being the main line that had other items in, i placed the new conveyors and the underflow gates got jammed.

**Comment by Quezler** [comment]
screenshot?

**Comment by Drac0nian** [comment]
Terribly sorry about not including a screenshot in the initial report as I had erased the evidence before I thought about reporting it, included is a screenshot of the issue, all the cryo mixers and bridges are full and the outer conveyors are there to prove that the gates have jammed, I hope this is enough. Sent from Mail for Windows 10 From: QuezlerSent: 22 March 2020 04:37 PMTo: Anuken/MindustryCc: Drac0nian; AuthorSubject: Re: [Anuken/Mindustry] Underflow gates jamming unexpectedly (#1736) screenshot?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Anuken** [comment]
@Drac0nian I need the real screenshot; you appear to have posted something random from your clipboard.

**Comment by Quezler** [comment]
~~thats just responding to a github issue from email gone wrong~~

**Comment by MEEPofFaith** [comment]
If you're chaining 2 Underflow/Overflow/Sorter/Inverted Sorter, It'll jam.

**Comment by Anuken** [comment]
Closing due to dead account and lack of screenshots.

**Comment by MEEPofFaith** [comment]
If I were to guess what they said, they were chaining underflow gates and are reporting that stacking underflow gates doesn't work.

That's a feature and it applies to overflows, underflows, sorters, and inverted sorters that placing 2 next to each other breaks it.

**Comment by MEEPofFaith** [comment]
I should read my own posts before posting.
