### ISSUE TITLE
Anti-feature: mod imports via the internet only allows Github

### ISSUE THREAD

**Issue by Wilker-a** [Anuken/Mindustry#1763]
Build 5-fdroid-104 as of now

currently, the mod imports using URLs only allows mods from Github to be downloaded, which not only limits the places where you can conveniently download directly via the game, but it also promotes a nonfree service as if it were the only place to host repositories on the internet (and by extension, the game mods).

the solution that i propose, is that instead of only having the repository address in the text box, the game should always ask for the entire repository URL address by default, regardless of the domain where it's hosted (with the box starting off as empty, with the ExampleMod's whole address being the ghost text), allowing the player to know more easily that they can get mods from places other than Github, and the "Import Github mod" should change to something in the lines of simply "Download mod", "URL import" or maybe "Git import" (as Git and Github are different things, and if it's the case that the game uses Git to download, too)

thank you for reading \^\^

**Comment by Anuken** [comment]
> limits the places where you can conveniently download directly via the game

How is this an anti-feature? If you want to use any other service, download the file and import it from your downloads folder. It's only a few more clicks.

> it also promotes a nonfree service as if it were the only place to host repositories on the internet

Github is used because it's (1) well known, (2) has a simple API to look up repositories by name and (3) has a tag/search system that can be used to index mods in a list. I'm not interested in adding support for other services or arbitrary URLs; if you think you can add a system to do so without impacting usability, submit a pull request.


In any case, the issue tracker is for reporting bugs, not requesting additional features. Closing.

**Comment by Wilker-a** [comment]
understandable. and thank you for the info

**Comment by Wilker-a** [comment]
just so i can know btw: what is there in the API to index mods if the only interaction with Github shown on the interface is to download a repository using `…github.com/:user/:repository-name`? woudn't it be more intuitive or easier to just allow the urls and have it as a domain auto-complete thing?

![Screenshot_](https://user-images.githubusercontent.com/10854855/77966904-8d268800-72d3-11ea-89a5-f22c1d63ed7f.png)![Screenshot](https://user-images.githubusercontent.com/10854855/77966923-94e62c80-72d3-11ea-956e-841bcfabf234.png)

###### screenshots taken from the current F-Droid build

**Comment by Anuken** [comment]
> what is there in the API to index mods

The game doesn't use indexing or display a mod list yet. It's a separate repo.

> woudn't it be more intuitive or easier to just allow the urls and have it as a domain auto-complete thing?

One *could* implement a system that takes the text input an determines whether it's a URL or an existing Github mod, then downloads the right file, but that wouldn't be a *github* mod dialog, and as I said earlier I'm not interested in implementing such a system.

**Comment by Wilker-a** [comment]
i see. so if i understood it right, implementing arbitrary URLs would impact usability because you believe it would be harder to future-proof it to implement the mod listing using Github's API, and therefore the dialog needs to be dedicated exclusively for Github, is that right?

**Comment by Anuken** [comment]
No, I just don't see much reason to replace the Github import dialog with something else. It's very simple to understand and use. If I replace it with something like "import from URL", users of the old system may not be able to tell that it can also be used to import Github mods by short name.

Not only that, but the whole idea of importing something via URL is pointless. I have yet to see a single mod hosted outside of GitHub, and if you have the URL at hand, why not just... download it? Again, selecting a file from your downloads folder is only a few clicks.

**Comment by Wilker-a** [comment]
i see. at first, this is nothing that a written sentence or two can't fix. people might not know what a URL is but they definitely know what an internet link is if that is the problem. it is also easy to just have a radio button for the domain and a ghost text for an example, and wherever necessary, a help button just like each and every item in the game already has. (optional documentation is never too much, there's always a chance that someone might not even know what a mod is, for instance.)

the second point however has two issues: the first one is for the interface itself. every time you build a program, there is a general idea [in the lack of a better word] that everything that takes more than three clicks to reach can be either difficult or frustrating to use, which can be a factor to actually discourage people from hosting their repositories elsewhere. although there are people who are willing to spend at least 5 to 8 clicks in total (considering only change of screens beginning from the main menu), it most likely feels like a punishment for not using Github when you can just spend 3 to paste a name and have it at hand instead.

the second issue is that it will make Github for repositories the same thing as what Youtube is for sharing videos or what Imgur is for sharing images or what Google is for searching the net — the common sense is that people will think what whatever name is thrown at them alone is the only platform that will ever exist for a given use case, which will only feed monopolies and make these have a lot more power over the users than it would be reasonable, because most people just don't bother to look at their surroundings when these aren't actually highlighted to them (you would be surprised with the amount of people who believes that Google is literally the whole internet). which is also the reason why i believe that the button dialogs should prioritize having a more open-ended language instead of single names. and besides that, just because there are no mods outside of Github today doesn't mean that there will not be any later, so future-proofing it for a more inclusive support for whatever new use case that will appear soon is important

**Comment by Anuken** [comment]
> this is nothing that a written sentence or two can't fix; a help button

I can tell you from experience: people rarely read extra text or click help buttons. Even if it's put in a dialog in their face.

> at least 5 to 8 clicks in total (considering only change of screens beginning from the main menu)

Why are you considering the change of screens from the main menu, when both methods require you to be in the same screen to use them? An actual comparison:  

*File method:*
  1. Click the download URL on the page in question, which should download it automatically.
  2. Press the "import mod" in the mod dialog.
  3. Press the "downloads" folder
  4. Select your file.
  5. Press "open". Done.

*URL method:*  
  1. Select/right-click the download URL on the page.
  2. Copy it (ctrl+c on desktop, but requires holding and pressing some buttons on mobile) or select "copy link address" if applicable.
  3. Press "import mod URL" in the mod dialog.
  4. Paste it in the box (ctrl+v on desktop, but requires a hold and a tap on mobile)
  5. Press "ok". Done.

Both methods are the same number of steps. Arguably, it's even *harder* on mobile than it is on desktop, due to the copy-pasting mechanism.

> which can be a factor to actually discourage people from hosting their repositories elsewhere

I don't see this as a problem. Having most mods exist on one site makes them easier to index.

> only feed monopolies and make these have a lot more power over the users than it would be reasonable

This is irrelevant. The dialog exists precisely *because* GitHub is a popular site for hosting repositories, and because GitHub's mobile site doesn't provide a button to download a repository. It's a small convenience. There is absolutely nothing stopping you from hosting the mod file anywhere you want, or even just sending people zip files. 

I'm not sure why you bring up Imgur here (as there are many image hosting sites, and I don't see it around much anymore), but in YouTube's case, one *can't* switch to anything else, because it's the only platform with a viewerbase. GitHub doesn't have this problem; one can switch to a different platform at any time - in fact, that's what many people did after this site was acquired by Microsoft. 

I don't see a problem with mentioning a service to others, when the service in question has a decent reputation and many alternatives.

> future-proofing it for a more inclusive support for whatever new use case that will appear soon is important

You say this as if importing a file from your downloads folder is a big hurdle for users, or that having a URL import box makes mod importing incredibly easy. This is not the case. 

To get a download link on GitLab, for example, you need to (1) right-click a small download icon, and (2) right-click the "zip" selection and copy its URL. Anyone who can figure that out should easily be able to import a raw file.

--- 

Regardless of what you think about GitHub, this doesn't belong here. The issue tracker is for reporting bugs, which this is not. You are asking for a feature to be implemented, and as I've said before, I am not interested in doing so.

**Comment by Wilker-a** [comment]
i feel like you've cut out some parts and addressed some others like i probably failed to make it clear that i have considered these cases, but i understood what you said.  
thank you for your time.
