### ISSUE TITLE
Power units don't auto-reroute on removal

### ISSUE THREAD

**Issue by alsonkemp** [Anuken/Mindustry#1854]
**Platform**: *Linux*

**Build**: Latest

**Issue**: If a multiply connected power nose is deleted the connected nodes/units don't reconnect automatically.  This is a common issue when replacing per nodes with large power nodes.  If a large power node is placed down and then the regular power node is deleted, any powered units are left disconnected.

**Steps to reproduce**: Delete a power node that could be routed around.  No new routes are created.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
custom code from nydus that might be of use, although it tries to reconnect (poorly) to all networks in range, and not the one that was severed: https://github.com/Anuken/Mindustry/commit/8fcaaf1e8bdf97b0786945591ccd4aef5e4d9553

**Comment by Anuken** [comment]
Power node aren't supposed to re-route automatically.

> Latest

"Latest" is not a build.

**Comment by DeltaNedas** [comment]
how can you play mindustry with just a kernel

**Comment by alsonkemp** [comment]
@DeltaNedas Not sure what you mean "just a kernel"?

**Comment by MWestfall** [comment]
@alsonkemp @DeltaNedas is attempting, poorly, to be a smartass implying that your "Platform" can't just be "Linux" because it's not an actual "distribution" but 1) the "kernel" is literally the platform.  If anything omitting the kernel version number was your only real 'mistake' not that it really matters, because the fact your on  Linux kernel in general is enough information for a "java based game" .... So instead of "Windows" I say Windows 7 8 or 10.  So if you had said "Linux 2.4" your Platform is now valid.  Long story short, there was no point in him even posting that at all. 

As Anuke already explained and told you that's designed behavior.  The solution is simple:  either delete the small nodes first, and drop the large, or drop the large, delete the small and double click the large.  It's literally just 500 ms of your life, vs changing designed game behavior.

**Comment by alsonkemp** [comment]
@MWestfall Fair (thank you for the explanation; though a pedant such as I should have expected it, I guess I've been sheltered recently from internet pedantry...).

FWIW: it's debian-testing (Gnome 3.3x)...

>As Anuke already explained and told you that's designed behavior.

Though I can imagine reasons for the behavior (none particularly good), I don't see most users expecting the behavior-as-designed...  In any case, it could be fun to fix locally (though I haven't written much Java since 2004).
