### ISSUE TITLE
AI is too easy to fool/influence to go through the doomhill

### ISSUE THREAD

**Issue by Kreyren** [Anuken/Mindustry#1887]
During my playthrough i found out that AI can be influenced to go through specific path by betoning the unwanted paths:

![image](https://user-images.githubusercontent.com/11302521/79627100-c6655180-8135-11ea-964f-d9960eacde39.png)

In this examples no matter what i do the AI will always choose the middle path (the most dangerous for them to take) which makes the game kinda boring..

Seems that the more connected walls there are the less likely the AI is to take that path.

### Expected behavior

The AI shoudn't be so easy to fool

### Proposed resolution

Spawn 5x more enemies, make them 3x stronger and less likely to group together with more randomness so that they could split to choose different paths on random -> Forcing the player to choose more complicated strategy

**Comment by Toxici11i** [comment]
`Spawn 5x more enemies, make them 3x stronger and less likely to group together with more randomness so that they could split to choose different paths on random -> Forcing the player to choose more complicated strategy`

Lets break down this HORRIBLE solution.

For one, spawning 5x as many enemies is just plain bloody stupid. ESPECIALLY at later waves.
Secondly, "make them 3x stronger". I seriously believe you have some sort of dent in your skull. This would make the map literally unplayable.
Thirdly, This would still be possible even with the new method, since a majority of the enemies still would go for the middle (the path of least resistance in its eyes) even when randomised, unless specifically told to not do that for the map.

Please, reconsider.

**Comment by nt314p** [comment]
Just wondering, how many waves did you survive? Or if you haven't died, how many waves are you at now?

Okay, maybe in earlier waves this combination of "fooling" and your defense works, but at some point, it will fail. That's the challenge of survival, to last as long as possible.

"Too easy" for you? Just wait for later waves.
"Kinda boring"? Don't play survival, because that's how the gamemode works.

I agree with @Toxici11i that you should reconsider your suggestion.

**Comment by Kreyren** [comment]
This was 60th wave right after the tutorial and first island (i believe) i figured out that i won't get any more rewards for surviving longer so i launched. I also calculated that i have unlimited resources since i have all mines indexed to distribute resources all over the map to distribute the ammo.

I would say that at least changing the way the AI thinks about walls should be considered assuming that if i beton half of the map they should see that for example left path does not have any guns for them to go through.

Assuming that making the game too hard is a concern maybe making some challenge mode for the survival that would make it more difficult to gather resources and more erratic enemies? 

maybe some randomizer for maps would be also great (alike forcing bridges over areas that are not accesible directly, etc..)

**Comment by Anuken** [comment]
I don't see how this is a bug. The walled-off path is not a very reasonable choice; there is far too much obstruction to get through in a reasonable amount of time. You are asking for the AI to take into account things like turret coverage, and that's not something I am ever planning to implement.

Play on a more difficult map. Frozen Forest is supposed to be easy.

**Comment by Kreyren** [comment]
@Anuken I've noticed the same "issue" on other maps as well 
![image](https://user-images.githubusercontent.com/11302521/79670809-f3f9db80-81c5-11ea-823a-0430413e92ac.png)

**Comment by Kreyren** [comment]
nevermind you close the issue, thanks for response.
