### ISSUE TITLE
Mindustry-BE-Desktop-8327.jar just dont start

### ISSUE THREAD

**Issue by CaptainCosmotic** [Anuken/Mindustry#2058]
**Platform**: *Windows 10 64 bit*

**Build**: *8316 8309 8318 8324 8327*

**Issue**: *If I double click the .jar file nothing happens. Version 8298 works fine. I did not test every version after that. Java claims it's up to date*

**Steps to reproduce**: *Don't know*

**Link to mod(s) used, if applicable**: *The mod repositories or zip files that are related to the issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
Don't play it.

**Comment by CaptainCosmotic** [comment]
What do you mean? I'm trying to support the development and find as many bugs as possible.

**Comment by Anuken** [comment]
I don't think this is a good time to test the game; there are potentially numerous crashes and bugs present that are caused by unfinished content (e.g. units being removed). The alpha would be a better time for testing.

In your case, I have no information to go off of. The game starts fine on my computer.
