### ISSUE TITLE
Sometimes, ressources stop being stored on multiplayer server

### ISSUE THREAD

**Issue by MasterBroki** [Anuken/Mindustry#2127]
**Platform**: Windows

**Build**: 104.10

**Issue**: I played a game with a friend and even though the conveyer belts were still rolling and the thorium coming in the core, the counter wasn't going up. 

**Steps to reproduce**: Still working on reproducing the issue

**Crash report, if applicable**: *The contents of relevant crash report files.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by LeoVen** [comment]
Not sure if related... but:

I've had similar issues with (what I believe) synchronization. There is this one sand that somehow got into a titanium conveyor going into the core. Only one of my friends saw this problem, but for everyone else, the conveyor was just fine with all the titanium going in.

Also, I've had occasions where someone couldn't delete a conveyor or a conduit. In this case, there was also the problem of certain resources not matching in each player's screen.

I wonder if these issues have been already fixed for 6.0. Or if there is any discussion about it. I haven't opened an issue on this because I couldn't reproduce it and it seems to be such a rare event that doesn't bother the gameplay at all.

**Comment by zethnest** [comment]
Have you tried doing `/sync`? Is the wave counter stuck at 0? Are the players moving? Are the enemies moving? Or there are no players in the player list but you and others can still chat with each other?

**Comment by Pota2s** [comment]
This happened to us when I was playing with my brother, the surge alloy goes in, and is immediately deleted upon reaching the core, it's fine when it's on containers not connected to the core but it makes us unable to build anything using surge alloys

**Comment by DeltaNedas** [comment]
use /sync

**Comment by Anuken** [comment]
Duplicate.
