### ISSUE TITLE
Sector copied and overwrites other sector

### ISSUE THREAD

**Issue by Cpppppppppplus** [Anuken/Mindustry#2570]
**Platform**: Linux

**Build**: alpha 105

**Issue**: When notification "under attack in another area" happens, clicking "go there", then going back to the previous section, causes the message "under attack in another area" to appear again. Clicking "go there" again, and then going back, causes the area where the attack is occurring to be replaced by the previous area.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TheMrAlbert** [comment]
This also happens to me too in Windows 64-bit. But I didn't report it due to unclear steps to reproduce.
What I remember is that I launched to next sector, then after few waves I go back to ground zero to research tech tree, after researching I decided to go back. But it copies and overwrites to other sector.
I was playing bleeding edge (I forgot which build number) and that happened. But because I have no clear idea how I did it, I didn't report it.
Anyway, hopefully the bug can be reproduced and patch. That's all my overall comment.

**Comment by Anuken** [comment]
I followed the exact sequence instructions listed, and no saves have been overwritten. I've also tried rapidly switching sectors, but nothing out of the ordinary has happened.

**Comment by Cpppppppppplus** [comment]
> I followed the exact sequence instructions listed, and no saves have been overwritten. I've also tried rapidly switching sectors, but nothing out of the ordinary has happened.

It happened on the second sector I took, which was the top-left sector from ground zero, and I think I may have clicked "ignore" or something like that the last time the attack warning appeared.

**Comment by Anuken** [comment]
I still can't reproduce this, and there isn't much to discuss in this issue. Unless it becomes a problem for *me*, it's not going to be fixed anytime soon. There's a non-zero chance of this issue randomly disappearing at some point due to internal changes anyway.
