### ISSUE TITLE
Full screen on iphone X

### ISSUE THREAD

**Issue by tregouetkevin** [Anuken/Mindustry#2744]
On iphone X, iphone 11 and bigger screen, game is not in full screen mode.

**Comment by Gdeft** [comment]
Nice template you got there and thank you for not providing the screenshoot either. Have you ever considered using the issue search bar to check if this issue is already reported? [This issue](#1647) exists.

**Comment by tregouetkevin** [comment]
![F47B09B6-04EC-4E96-BF75-1B8CCD150742](https://user-images.githubusercontent.com/4193050/94358501-c765bc00-00a1-11eb-894e-df6f174504f9.jpeg)

Sorry this is the screenshot

**Comment by tregouetkevin** [comment]
And i cannot find any issue about this...

**Comment by DeltaNedas** [comment]
don't use screens with holes cut in them

**Comment by tregouetkevin** [comment]
?? there is no cut...

**Comment by Gdeft** [comment]
> And i cannot find any issue about this...

I already gave you the link.

**Comment by tregouetkevin** [comment]
do you have try your link ?

**Comment by RogueRedHawk** [comment]
#1647

**Comment by tregouetkevin** [comment]
> #1647

Thank buy why this issue is closed ?

**Comment by Anuken** [comment]
It's not supposed to be fullscreen. Mindustry doesn't support it, and screenshots on the App Store explicitly show black borders.

**Comment by tregouetkevin** [comment]
you have screenshot in the app store in full screen mode.... i think you need to consider better your port on mobile... since its a paid game !

And if i remember apple will no longer accepte app and game who doesn't support the fullscreen mode

**Comment by tregouetkevin** [comment]
![E66C385E-78D9-424C-8F54-21FD5452D50D](https://user-images.githubusercontent.com/4193050/94367099-a9697d00-00dc-11eb-8bd9-5442c50f9ff1.jpeg)

From the apple store

**Comment by Anuken** [comment]
> you have screenshot in the app store in full screen mode

Those are cropped world images without UI, and not supposed to represent a real device. The two screenshots on the left and right **clearly** show black borders, they're hard to miss. 

Especially on the app store:

![image](https://user-images.githubusercontent.com/10100000/94367168-e3219000-00aa-11eb-88bd-e1ac02555d8b.png)

> And if i remember apple will no longer accepte app and game who doesn't support the fullscreen mode

If they didn't, Mindustry would not be on the App Store.

> i think you need to consider better your port on mobile... since its a paid game !

Mindustry on iOS is paid because the platform forces me to pay annual feels to use it, not because it has more features. I will not be adding fullscreen support, as that breaks nearly every single UI element. Working with mobile is hard enough as is.

**Comment by tregouetkevin** [comment]
As you want, your game is really good, it's a shame not to improve this mobile version.

GL

**Comment by itcannotbe** [comment]
The android version works great. Thank you for asking. *sarcasm*

**Comment by tregouetkevin** [comment]
> The android version works great. Thank you for asking. _sarcasm_

wait, what is android ? :p
