### ISSUE TITLE
Builder drones dont connect bridges

### ISSUE THREAD

**Issue by CaptainCosmotic** [Anuken/Mindustry#2794]
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows*

**Build**: 10140.*

**Issue**: *When builder drones construct your bridges they don't connect*

**Steps to reproduce**: *Create a custom Map and get some Polys now build bridges outside of your building radius. When you build them they will connect. If the Polys build them they won't*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The save file you were playing on when the bug happened. REQUIRED for any issue that happens in-game.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
They're not supposed to.

**Comment by CaptainCosmotic** [comment]
Very annoying if drones are next to you : (

**Comment by CitrusWire** [comment]
+1 this bug is getting me too. The entire point of Poly's is to rebuild chunks of your base after the AI has wiped them out. If it's missing crucial repairs out, then doesn't that obviate part of the purpose of the Poly's? It's not reasonable for a player to be keeping track of all their bridge connections on top of everything else.
