### ISSUE TITLE
onProximityUpdated called far too many times, and in the editor

### ISSUE THREAD

**Issue by DeltaNedas** [Anuken/Mindustry#2885]
**Platform**: Android 9

**Build**: 10305

**Issue**:
When an adjacent block is placed, onProximityUpdate is called **6** times instead of once or maybe twice.

![a](https://user-images.githubusercontent.com/39013340/95576933-d2fd9f00-0a20-11eb-89cb-6c335d870009.jpg)

Related: onProximityUpdate is called in the editor, probably not intended. (Trying to fill a 50x50 map with arc routers froze my phone for about a minute)

**Steps to reproduce**:
1. Clear log
2. Place test block and see Created, Prox updated (correct)
3. Place a block next to it and see ~5 erroneous Prix updated's

1. Make a map
2. Fill/place test block
3. Look in F8

**Link(s) to mod(s) used**: [testcase.zip](https://github.com/Anuken/Mindustry/files/5354555/testcase.zip)

**Save file**: [test.msav.txt](https://github.com/Anuken/Mindustry/files/5354551/test.msav.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

Please don't fully close this unless both related issues are fixed/invalid

**Comment by Anuken** [comment]
> ~5 erroneous Prix updated's
 
A couple of these are (probably) erroneous, but many are required:
1. nearby block gets set to ConstructBlock, prox update
2. nearby block gets removed (no longer ConstructBlock)
3. nearby block set to new target block, whatever that is

IIRC some blocks, like the plastanium conveyor, had some complicated blending problems that required a lot of updates to settle properly. That's why there's redundancy. I can remove a couple of the updates and hope it doesn't break anything, but you should really try not to put any significant logic inside onProximityUpdate`.

> Related: onProximityUpdate is called in the editor, probably not intended. 

I *can* disable that, but for non-modded blocks this was never a problem and I had no reason to change it.
