### ISSUE TITLE
AoE damage is very overpowered against larger blocks

### ISSUE THREAD

**Issue by Syncinus** [Anuken/Mindustry#2890]
**Platform**: Windows 10

**Build**: Custom build, latest version

**Issue**: From digging through the code, it appears that AoE splash damage can apply multiple times to a multi tile block. so if it hits all tiles of the block, it isn't even doing normal levels of damage anymore, it's basically just draining away from the health per tile of the block, which makes multiblocks with super high HP affected the same as if it was seperated up into a bunch of small blocks. This also causes things like big unit crashes to do stupidly high amounts of damage and is why they used to one shot cores. I don't know if this classifies as a bug or not, or if it is a suggestion to change it.

**Steps to reproduce**: Use an AoE weapon against a multiblock, or crash a large air unit into a multiblock, it will do much more damage then expected.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
I am aware of this, and will not change the behavior for several reasons:
1. It messes with game balance. Even if you think this is overpowered, the current state of splash damage weapons seems fine to me.
2. Let's say you have a 2x2 chunk of 1x1 walls. If splash damage hits them, **3-4** of those buildings will receive individual splash damage; the **total** amount of damage dealt will be approximately 3-4x the base splash damage. Now, if you replaced that chunk of walls with one 2x2 wall, you would get the same situation and the same 3-4x amount of damage dealt - except, this time, it's technically one building taking all the damage. *But that shouldn't matter*, because the total amount of damage is the same. Only dealing 1x the splash damage would actually make splash damage *underpowered* against multiblocks.

**Comment by Syncinus** [comment]
I guess that makes sense
