### ISSUE TITLE
Units don't move

### ISSUE THREAD

**Issue by Arawetia** [Anuken/Mindustry#2998]
![Screenshot_2020-10-17-14-30-59-152_io anuke mindustry](https://user-images.githubusercontent.com/73030155/96346389-df769d00-109b-11eb-9322-ed996b005284.jpg)

The units sometimes don't move when a new wave starts and you can hardly get to them

**Comment by Quezler** [comment]
wrong issue template, close this.

**Comment by XEN0PHIL** [comment]
Oh god what is this influx of idle unit reports, and all of them have a borked template
Please close this issue, this bug was already [reported](https://github.com/Anuken/Mindustry/issues/2936) and [fixed](https://github.com/Anuken/Mindustry/commit/6b4a7d025b20f6d2cb7b8722204fa7b9a316fdfa) (but not released yet)

**Comment by ThePythonGuy3** [comment]
This one is the third one today, god
