### ISSUE TITLE
#2977 persists

### ISSUE THREAD

**Issue by Legomonster33** [Anuken/Mindustry#3358]
**Platform**: *Android/iOS/Mac/Windows/Linux* windows 10 64 bit

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* beta 113.2

**Issue**: *Explain your issue in detail.*
#2977

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
#2977

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
N/A

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
happens across saves.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
it has but it persists

**Comment by MEEPofFaith** [comment]
> THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.
> **REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE.**

**Comment by Legomonster33** [comment]
> > THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.
> 
> > **REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE.**

I literally tested it on 4 separate save files, on 2 separate devices, it happens regardless of save file.

**Comment by Legomonster33** [comment]
Also it's an elaborate one time setup that cannot be demonstrated with save files

**Comment by Anuken** [comment]
1. This is the sector that I just watched get destroyed. You can see that I've been there, because it has all the resources discovered.

![Screenshot from 2020-11-12 09-29-09](https://user-images.githubusercontent.com/10100000/98952585-a0384200-24c9-11eb-8d3a-512fc512dac1.png)

2. Items selected.

![Screenshot from 2020-11-12 09-29-14](https://user-images.githubusercontent.com/10100000/98952588-a0384200-24c9-11eb-8830-1102c9f134aa.png)

3. ...and the items are all there when I arrive.

![Screenshot from 2020-11-12 09-29-37](https://user-images.githubusercontent.com/10100000/98952589-a0d0d880-24c9-11eb-8eba-438d88680cc2.png)


**This is exactly why I ask for your save file. Stop wasting my time with incomplete reports.**

> Also it's an elaborate one time setup that cannot be demonstrated with save files

How is it difficult to just send me the data zip right before you are about to launch, then tell me where you were launching in the report?

**Comment by Legomonster33** [comment]
1. load this save file
2. launch to sector 145 (one of the few remaining sectors available for launching to)
https://drive.google.com/file/d/1IiMNJ3JySI3HpzfCD9_55ljMX7hH9lLm/view?usp=sharing
3. have no items

**Comment by Anuken** [comment]
In your save, 145 is captured:

![image](https://user-images.githubusercontent.com/10100000/98970139-98829880-24dd-11eb-85f3-e45928d3c186.png)

I tried to reproduce it anyway by going to 145, killing the core, then launching from a random sector. Note that I had to remove copper and lead from your loadout because I didn't want to search for a sector that had sufficient amounts of it.

...and everything expected was there.

![image](https://user-images.githubusercontent.com/10100000/98971095-b7cdf580-24de-11eb-9cb8-2f94c70ccf0a.png)


I then tried to import your save **again**, kill the core **again**, fill a nearby sector with items, and launch with a full loadout (no settings changed).

![Screenshot from 2020-11-12 12-06-42](https://user-images.githubusercontent.com/10100000/98971987-de406080-24df-11eb-88f4-3e1b2aad4e40.png)

![Screenshot from 2020-11-12 12-07-21](https://user-images.githubusercontent.com/10100000/98971998-e1d3e780-24df-11eb-8d77-63baf1dae9d9.png)

...and it was still full of items.

**Comment by Legomonster33** [comment]
![image](https://user-images.githubusercontent.com/54417042/98972255-32e3db80-24e0-11eb-8005-eef0dfb06c12.png)

![image](https://user-images.githubusercontent.com/54417042/98972505-822a0c00-24e0-11eb-9c5b-f5cd1864ac07.png)

**Comment by Legomonster33** [comment]
> How about actually sending me the save with the sector uncaptured so I can test it properly?

when i exported the save sector 145 was uncapped

**Comment by Legomonster33** [comment]
and now i dont have any more sectors that i need to revisit,
it only seems to happen with sectors that were lost in prior versions as i can only replicate it by doing some version switchy shenanagins, so it likely isnt a real issue rather an odditie due to version shifting.
