### ISSUE TITLE
Terrible mobile naval unit control

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#3477]
**Platform**: *Android/iOS*

**Build**: *105+*

**Issue**: *Mobile naval controls are frustrating to use, with the ships making giant, unnecessary banking turns and getting caught in enemy fire.*

**Steps to reproduce**: *Exist as a naval unit on mobile.*

**Link(s) to mod(s) used**: *null*

**Save file**: *(I really suggest specifying if it is save specific) null*

**Crash report**: *null*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have been watching the closed and open issues to see if this would be reported but eventually got annoyed and did it myself.**

**Comment by YellOw139** [comment]
And why do you think on PC it's easier?
Navals are harder to control than the average unit, but that's by design.

After a few local PvP games with my sister last month, featuring naval units, I didn't get frustrated, and neither did she.
Sometimes it's easy, sometimes it's hard, but I find them just as easy (or hard) to control on both platforms.
