### ISSUE TITLE
Negative global resource after exit from a multiplayer game

### ISSUE THREAD

**Issue by gitfish256** [Anuken/Mindustry#3538]
**Platform**: *Windows*

**Build**: *115*

**Issue**: 
1. After playing on a random online server (not community server), I got average 30-50k resources for each, with a newly created campagin save. 
-> Should I get this much resouce when back to single player?

2. I spent some of them unlocking the research, and found the sector I played in multiplayer was still in my campagin map, so I got in and played for a while. 
-> Should I be able to see multiplayer sectors in single player campagin?

3. After this, I found some of my global resources became a large negative value (e.g., -200k).
-> I would say this is a issue for sure.

**Steps to reproduce**: 
I haven't tried reproduce it, but my save was randomly back to normal (positive resource) and got back again when switching from sectors, so it's hard to say how to constantly reproduce the problem. However, my save is in a state that the negative value keeps changing even after upgraded to 116 and restart the game, so I hope the save file would help.

**Link(s) to mod(s) used**: *N/A*

**Save file**: [bugreport.zip](https://github.com/Anuken/Mindustry/files/5581011/bugreport.zip)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
There is a similar one but it has been fixed https://github.com/Anuken/Mindustry/issues/3189

**Comment by gitfish256** [comment]
![image](https://user-images.githubusercontent.com/29269751/99927708-2e4ace80-2cfb-11eb-8f62-1891a859b7c2.png)

**Comment by Anuken** [comment]
1. I don't see why this would happen. Without knowing what saves you were playing on in multiplayer, I can't figure out what happened. Your campaign should not update when playing on others' games.
2. This was fixed in 115.
3. This could be related to 1) overflowing your resources, but again, all the information your saves give me is that your resources are negative. There is no indication of why it happened.

I can add some extra checks, but without knowing the real cause this can't be reliably fixed.
