### ISSUE TITLE
Co-op Research doesn't sync in 6.0 Public Release

### ISSUE THREAD

**Issue by rar8022** [Anuken/Mindustry#3711]
**Platform**: Windows

**Build**: steam build 120.2

**Issue**: When playing a co-op with a host and client, when the client leaves the host game there are no unlocks that makes its way into their campaign data. This kills any benefit to multiplayer if you have to do everything twice (once on host, and then swapping to client). Playing with friends is mostly about shared progression, which is completely capped now. I understand limiting resource sharing that existed in 5.0 where joining and launching from someone's game / server ended up netting you resources, but this feels like overkill.

https://steamcommunity.com/app/1127400/discussions/0/2961643431524056393/
https://steamcommunity.com/app/1127400/discussions/0/2992039579110366350/

**Steps to reproduce**: Play with Host and Client

**Save file**: [sector-serpulo-142.zip](https://github.com/Anuken/Mindustry/files/5627164/sector-serpulo-142.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by buthed010203** [comment]
No more leeching off of friends, its not a bug lol

**Comment by Anuken** [comment]
> When playing a co-op with a host and client, when the client leaves the host game there are no unlocks that makes its way into their campaign data.

This is intentional. The campaigns for each player are completely separate; unlocking research when the host does wouldn't make any sense.

Consider the following situation:
- Host is well into the tech tree
- New client joins host
- Host researches advanced tech, e.g. thorium reactor

What should happen in this situation? Should the client get all the host's research immediately, despite the fact that they weren't there for most of it? That seems very wrong, and looks like an exploit to me.

Or should they *only* get a thorium reactor that they can't even use, and for which they don't have the right materials? It'll just end up floating in the tech tree with no connecting nodes.

Also consider the following situation:
- Host opens game with no progress
- Client joins, and they play together, researching everything
- Client disconnects
- Client now has a full tech tree, but no resources or captured sectors, so they can't *use* anything. There is no viable way to "sync" the hosts's captured sectors to the client, because the saves are completely different. Duplicating them wouldn't make sense.

**Comment by rar8022** [comment]
Thanks for answering. This wasn't a "mooch" situation as legitimately my buddy and I enjoy playing co-op and both benefiting. We didn't see any details other than the research being separated out to indicate that there was intention behind it, so we wanted to clarify.
