### ISSUE TITLE
Unable to Passively Export Stockpiled Resources

### ISSUE THREAD

**Issue by TeabagNation** [Anuken/Mindustry#3778]
**Platform**: Windows

**Build**: Steam 120.3

**Issue**: Sectors that aren't currently being focused on will not continue to export any resources that they aren't producing, even if they have a stockpile to export from.

**Steps to reproduce**: Have sector A use the launch pad to send a resource to sector B. In sector B, have only an unloader from the core and a launch pad to sector C (and power). If you watch sector B you'll see the resources being launched, and will be able to go use them in sector C. However if you go to the planet map and check info, Sector B will show nothing for current exports. Also, if you focus on sector C no resources will trickle in - they only get launched while focus is actually on sector B.

**Link(s) to mod(s) used**: No mods

**Save file**: [saves.zip](https://github.com/Anuken/Mindustry/files/5645207/saves.zip)

**(Crash) logs**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is intentional. Stockpiled resources cannot be exported passively.

Consider this situation:
- Player lands on a sector with a certain amount of resources
- Player fills random unconnected vault with surge alloy
- Player begins unloading vault into a launch pad, then immediately leaves once the first batch launches
- Player now has infinite surge alloy being launched from that sector despite the fact that they have no production

A possible workaround is to heighten the cap when production is negative, but that has not been implemented yet.

**Comment by TeabagNation** [comment]
Well, in this case the intention wasn't to stockpile resources, but to have a hub that all exports flow through, so that it's easy to redirect all of the resources to a new sector after launching.

I guess there's a technical limitation that prevents the stockpile from just being launched until it runs out. The export rates must be based on a snapshot from the last time the sector was focused, and not actually constantly calculated?
