### ISSUE TITLE
iOS: Freezes/Crashes

### ISSUE THREAD

**Issue by PwnHammer007** [Anuken/Mindustry#380]
Hello, I downloaded Mindustry recently on iOS. While I absolutely love the game and the incredible potential this game has I encountered several instances where the game would freeze. This problem has occurred in non-custom maps, custom maps of my own design, during the creation of custom maps in the editor. Other than this rather annoying occurrence I have enjoyed the game very much, personally the cost for the game on the App Store was very generous for how much there is to do.

**Comment by ZacBytes** [comment]
What Apple device do you have and what version of the game are you running?

**Comment by Anuken** [comment]
You are not the only person to report issues with the 3.5 iOS build, but I think some of these issues may have been fixed in 4.0 with newer versions of RoboVM. I don't have an iOS device to test on, and at this point the symbolication files for the 3.5 version are long gone; thus, I will be unable to find out whether or not the issues have been fixed. 

If crashes continue in 4.0, I'll see if I can acquire an iOS device and properly symbolicate the crash logs, but for now I'll close this issue since I can no longer act on it.
