### ISSUE TITLE
Plastanium conveyor bug

### ISSUE THREAD

**Issue by Horn772** [Anuken/Mindustry#4128]
**Platform**: *Windows (7)*

**Build**: *steam 122*

**Issue**: *Dropping any items to plastanium conveyor after mining*

**Steps to reproduce**: *https://youtu.be/sMwk07LGbNs*

**Save file**: *[router.zip](https://github.com/Anuken/Mindustry/files/5742892/router.zip)*

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment]
i have pinpointed the issue, its `Call.transferItemTo` (the amount can be `0`)

the problem only really seems to occur when commanding units, since the last item they carried isn't exactly erased, just set to zero, which kinda creates a strange race condition in the plastanium conveyor when deciding which item to render.

the function gets called from several different places, and the call itself does have a `Math.min` that allows zero, so i'm not exactly sure what the best way to fix it would be, as long as `handleStack` never allows zero for the amount it'll be fine 🤔
