### ISSUE TITLE
Serpulo's star is too small to be able to be a star

### ISSUE THREAD

**Issue by BlueManedHawk** [Anuken/Mindustry#4153]
**Platform**: `GalliumOS 3.1 running on ASUS Chromebook Flip C302C (*not C302CA!*)`

**Build**: `Release Build 122`

**Issue**: *Serpulo's star is aroundabout the same size as Serpulo itself.  Therefore, it would logically be too small to be able to undergo fusion, yet somehow it does.*

**Steps to reproduce**: *Look at the solar system map.  Tada!*

**Link(s) to mod(s) used**: `I am not using any mods.`

**Save file**: *I don't _think_ this constitutes being in-game, so I don't think this is necessary.  If it is, I'll add it.*

**Crash report**: *This isn't a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
1. You assume that Mindustry runs under the same laws of physics.
2. You assume that the planet map is an accurate representation of size or distance proportions, which it clearly isn't. Very few games are accurate in this regard, for good reason.
3. You don't know how large or dense Serpulo is, yet you "logically" assume that a sun of the same size is too small to undergo fusion.
4. You are filing a bug report when this is *clearly* not a bug.

**Comment by BlueManedHawk** [comment]
- I would assume that it would be safe to assume that Mindustry uses normal physics.  It certainly appears to in many regards.
- Could you please tell me why it "clearly isn't" and what this "good reason" is?  
- ...Alright, yeah, I don't really have anything to say about that one.  My mistake.  I should have done some research.
- I'm pretty certain that this is a bug, but I can reopen it in the suggestions repository instead anyway.

**Comment by Anuken** [comment]
- Nope.
- This should be obvious. Take a look at [this visualization](https://joshworth.com/dev/pixelspace/pixelspace_solarsystem.html) and compare it to the distances between Serpulo and the sun in the game. Nothing shown in the planet map is even **remotely** similar. For more comparison, [see what a random Stellaris solar system looks like.](https://cdn.player.one/sites/player.one/files/2016/05/13/stellaris-star-system.jpg) Or [this system](https://www.icomedia.eu/wp-content/uploads/2015/07/Endless-Space-2-Curiosities.jpg) from Endless Space 2. Note how the suns are all relatively small - certainly too small to undergo fusion.
- Claiming that the sun is "too small to undergo fusion" is utter rubbish, because *any game with a solar system overview will have completely unrealistic sizes and distances.* A "realistic" solar system map would be useless.
- *Why would it be a bug?* All the sizes are perfectly intentional.

**Comment by BlueManedHawk** [comment]
- Huh.  Alright then.  I'm curious as to what physics it _does_ use, but I suppose that's outside of the range of this thing.
- Well, it wasn't obvious, and I'm glad you explained it to me.  Thank you!
- Yes, you just explained to me that it was a metaphor.  (That may not be the right word.  I hope you understand what I mean.)
- Again, I'm pretty sure this is a bug, but frankly, I'm not going to argue this, since that never ends well.

**Comment by Anuken** [comment]
> Again, I'm pretty sure this is a bug

In this case, bugs are unintentional or unforeseen behavior. The size of the sun in Mindustry is neither, and not even particularly unusual.

**Comment by BlueManedHawk** [comment]
Sorry, I didn't word that right.  What I was trying to say was this:

Had the only reason for this ticket closure been "This is not a bug", I would have been moderately disgruntled, but entirely willing to post to the Suggestions repository; however, you have given me a perfectly good explanation as to why this isn't a problem, and therefore I will not report it as a problem.

**Comment by XxsuperdeadlysniperxX** [comment]
Bruh wot an arguement about mindustries sun incredible i love gihub

**Comment by BlueManedHawk** [comment]
@XxsuperdeadlysniperxX  , I can't tell what you're saying.  Could you please restate that differently?

**Comment by XxsuperdeadlysniperxX** [comment]
Oof typos happened what i said is i love these strange arguments that happen on github
