### ISSUE TITLE
Screen sharing on discord makes level editor UI flicker.

### ISSUE THREAD

**Issue by AtobaAzul** [Anuken/Mindustry#5482]
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Steam build 127.1
**Issue**: *Explain your issue in detail.*
When screen sharing mindustry, the ui of the level editor flickers, it seems to also depend on the FPS of the screen sharing.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Join a voice chat in discord, start screensharing mindustry, go to the level editor.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
This is an issue with Discord, not Mindustry.

**Comment by geneotech** [comment]
We had the exact same problem [in our open-source shooter.](https://github.com/TeamHypersomnia/Hypersomnia)
Games often use a certain optimization technique: you check if the GL texture is already bound before calling ``glBindTexture``, and if it's the same texture, the call is skipped to save on OpenGL calls.

**That optimization turned out to be the culprit:**
https://github.com/TeamHypersomnia/Hypersomnia/commit/99de1cc851d33915eacb3b6166397008d296fad2

My hypothesis is that Discord streaming and Steam overlay happen to make their own calls to ``glBindTexture`` in-between frames, and the CPU-side identifier simply becomes out of sync.

I also took care to call ``glBindTexture`` especially right before every call to ``glTexImage2D``.

**Comment by Anuken** [comment]
Doesn't rebinding the texture unnecessarily incur a significant performance penalty? It seems like a significant price to pay...

**Comment by geneotech** [comment]
> Doesn't rebinding the texture unnecessarily incur a significant performance penalty? It seems like a significant price to pay...

It doesn't for us. Depends on the game: it shouldn't make a difference unless the rendering pipeline is extremely badly designed - e.g. if it calls glBindTexture for every single object on the scene. Most of the time though, any game will make just several calls to ``glBindTexture`` per frame, so saving a call or two is completely insignificant, yet it's enough to cause flickering when some kind of overlay application tries to inject its own code.

I'd also expect some drivers to make a check internally anyway.
