### ISSUE TITLE
[Logic-Specific] Get link cycling ignores all but the first turret/building linked during session when outputting radar target info

### ISSUE THREAD

**Issue by T-oasterO-ven** [Anuken/Mindustry#6123]
**Platform**: *Windows 10*

**Build**: *steam build 131*

**Issue**: Was modifying a [unit control logic processor](https://steamcommunity.com/sharedfiles/filedetails/?id=2360425487) (by TheNightglow). After the initial [modification](https://pastebin.com/0nERbKdi) to get it to work with another processor (and a few other smaller changes) and a round of debugging, there still remained a problem that didn't seem to match what had been written in mlog.

For some reason the code seems to only detect the first building I link. Individually linking to only one turret always works, but when there are multiple----some turrets are completely ignored (target info always comes out as null---when they shouldn't, despite the [link cycle var](https://mindustrygame.github.io/wiki/logic/3-variables/#links-constant-number) cycling normally). Also, in that situation, **the first turret linked ever (during session), seems to get priority while the others ignored, reloading back into the session with the processor "delinked" from all turrets is the only way to change which turret isn't ignored.**

I [contacted](https://steamcommunity.com/sharedfiles/filedetails/?id=2360425487) (in WS comments; visit for more context) the original creator of the schematic I was using who said he had encountered the same issue in the base design after testing again---his design worked back in February when he created it---no longer.

Normally the mlog code speaks for itself, and when it doesn't it is either a bug or a new addition/rework, after combing through the recent Minndustry Github changes (back to Feb. '21), there is nothing to indicate that this isn't a bug, but if I'm wrong sorry for any inconvenience I might have caused here (don't reap my soul plz).

Although, after searching /issues, this may or may not be related to #4891
(does not involve link cycling of any sort though, in the end, probably unrelated, except with the whole save and load being the only way to switch the 'turret that doesn't get ignored' when linking multiple turret radars).

**Steps to reproduce**: 
1.) Sub to the [workshop schematic](https://steamcommunity.com/sharedfiles/filedetails/?id=2360425487)/Open save file
1.25.) Started a Maze sandbox map.
1.5.) (built command center with repair points)
2.) Created 24 flares
3.) Placed down schematic.
4.) Linked a foreshadow.
4.5.) (Start wave. Flares rush the enemy when in range of the foreshadow)
5.) Add and link a 2nd foreshadow just in front of the first one (so enemies will hit the new foreshadow range first)
6.) Start next wave. 
7.) Flares ignore the new foreshadow entirely, despite logic debugging showing no sign of the link cycler stopping/breaking, and it working before (back in FEB 2021).
8.) Reloaded save, still an issue.
9.) Reloaded after delinking, then I linked the 2nd foreshadow then the 1st one (aka reversed), this time the flares don't ignore the 2nd turret, but now they ignore the 1st one.

10.) Peer review your schematic to make sure you actually RTFM and GitHub changelogs.
11.) Conclude that this must be a bug and that the first turret linked during the session seems to be the only turret not ignored in [link cycling](https://mindustrygame.github.io/wiki/logic/3-variables/#links-constant-number).

**Link(s) to mod(s) used**: Only used RTFM and Simple Walls on the save below.

**Save file**: The (zipped) save file I was playing on when the bug happened: 

[11.zip](https://github.com/Anuken/Mindustry/files/7313934/11.zip)

zip contents: 11.msav

**(Crash) logs**: *N/A*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
That schematic works for me, at least partially.

![image](https://user-images.githubusercontent.com/10100000/136626445-c659e0ea-9fdb-4295-bb81-3f15f30b07ab.png)

The foreshadow shown was linked only after the first (left) one was verified to be working, and the enemy unit is only in range of the second foreshadow.

> the first turret linked ever (during session), seems to get priority while the others ignored

What does this mean? Links don't have a defined "priority", they are inserted into the list in more or less random order.

> ignored in link cycling.

This sounds like something specific to your schematic. When I delete most of the code in the processor and replace it with a simple program that prints any targeted unit from multiple turret radars, it works fine, e.g. cycles through both turrets and prints units that could only have been in range of one specific turret.

![image](https://user-images.githubusercontent.com/10100000/136627402-62e5865e-ba6d-49c7-b908-7fa5bae6b692.png)

---

Sorry, but I don't debug entire logic programs here. Unless you can specify **exactly** what the bug is, I can't classify it as a problem with the logic system. You could be relying on undefined behavior, or a specific order of links, or even a bug that has since been fixed.

A *specific* bug report would be something like:

- "link 0 is null when there are clearly multiple links here"
- "using radar from link 0 doesn't at all work in situation X"'
- etc.
