### ISSUE TITLE
Consider adopting a translation platform

### ISSUE THREAD

**Issue by osoitz** [Anuken/Mindustry#628]
I recently uploaded a new translation. GitHub is easy to use, but it lacks some features found in translation platforms that come handy.

Any decent translation platform:

- Syncs with GitHub.
- Makes *very* easy to keep up with new strings or changes in the original language text. (No need for diffs or anything like that)
- Has adequate search functions and gives access to a translation memory, that helps in maintaining quality and consistency.
- Facilitates a collaborative translation, it's easier to contribute a single correction or suggestion.
- Is used by other projects, so for translators of several projects it's less probable to forget about any of them.

However:

- It's a piece more in your workflow, despite the automated sync and import-export tools
- Might have file format requirements (No idea if the current one meets them)
- Translators might expect you to check the translation platform every once in a while, they usually allow to make comments to indicate that a source string has a typo, or to ask for context...

So is it worth it?

Some time ago I calculated stats for apps in F-droid and it was much more likely for an app to have an up to date translation (or any at all) when the project used a translation platform vs Git. I only checked one language but I'd bet that's general.

Which translation platform?

There's both self-hostable software and online services, most of the projects opt for an online service (those that prefer to self-host are usually very big projects).

I like Hosted Weblate. It's FOSS itself and gratis for FOSS projects. While not the most feature-full, it has all the basics covered and I feel that this simplicity is an advantage for casual translators.
https://weblate.org/en/hosting/

Other two that must be mentioned are Crowdin and Transifex, they aren't FOSS themselves but offer the service gratis to FOSS projects. Both are very feature-full and popular. I personally prefer Crowdin among these two, I still get lost in Transifex after years using it.

Other less common options are Zanata, PoEditor, Pootle...

Thanks for reading, now I have some copper to mine.

**Comment by valtsu41** [comment]
I think some people used something unofficially sometime.

**Comment by YaFou** [comment]
Very good issue!

I know a famous platform for translations: **[Crowdin](https://crowdin.com/)**. There is a plan for open-source projects totally free. I think it's a good way for a first translation tool.
*What're your opinions?*

**Comment by PetrGasparik** [comment]
I have quite a good knowledge of [Transifex](http://www.transifex.com). It solves a lot of troubles.
- collaborative
- autopull of changes from github
- history of changes in tranlations
- suggestions on translation
- dictionary if you need to define terms

Push to github is not straightforward, has to be done by webhooks. On project that I manage (Evolveum midPoint, 14 languages, 5 thousands keys) I do that by bash file.

**Comment by PetrGasparik** [comment]
Another reason to adopt translation platform: translating the changelogs is tedious task. One have to check so many places to be sure everything is up to date.

Also, pure bundle translation means: I have to check all commit and remember which one I translated last. Then, I have to go line by line.
Compare this to ability to translate things by opening translation platform page with list of all changes waiting to be translated.

**Comment by PetrGasparik** [comment]
Examp,e of another platform: https://translate.mattermost.com/cs/

**Comment by PetrGasparik** [comment]
One more point:
Right now, out of 59 open PR, 16 is for translations, more than 1/4.
Some of them are really old and may or may not be easily merged into master. Maybe they are overriden by newer translation. Maybe not.

Translation on right platform would lead to 
- smaller count of PR
- everyone always work with the same dataset (wordset)
- no outdated changed waiting for approval

What is @Anuken 's point of view on outsourcing translation?

**Comment by Anuken** [comment]
Using a new platform might be a better idea, but there are at least 3 choices now, and many users will most likely continue using raw PRs to propose translations. I would need to try out each platform and see which one works best.

**Comment by PetrGasparik** [comment]
Yes, that would make sense, @Anuken. I bet you realize that every time you have to go through translation merge before new release :)

May I help you here in any way?

**Comment by ImUrX** [comment]
My only comments on this is that crowdin is free for open-source projects and it has implementation with github. I havent tried if editing the code in the github side updates strings in crowdin side (will try it when i implement some new strings)

**Comment by int-ua** [comment]
When I tried to use Transifex the last time to translate CDDA it was too slow to use comfortably. Locally the delay to switch to the next translatable message / row is miliseconds while on Transifex it took more than a second just to switch rows.

**Comment by PetrGasparik** [comment]
Yeah, sometimes. But most of times, it is ok for me.
--
Petr G.


po 9. 11. 2020 v 10:38 odesílatel Serhiy Zahoriya <notifications@github.com>
napsal:

**Comment by Bohaska** [comment]
This issue hasn't been resolved for years. Do we have an answer for this?

**Comment by jimmy927** [comment]
How are those platforms integrated into the current workflow ?
How would it integrate ?
Do we just ask their API and build the current textfiles as artifacts in the CI/CD workflow ?

**Comment by Anuken** [comment]
Taking another look at Crowdin and Transifex, I noticed this:

> We offer Transifex for free to Open Source projects that have **no funding, revenue, and/or commercialization model.**

> If you're building awesome **non-profit** projects that could use the power of Crowdin, we're happy to help.

This means that Mindustry is ineligible for these platforms; I would have to pay **at least** $50 a month to use either of these services. That's something I would rather avoid.

Weblate seems to support self-hosting, but looking at some example projects, the UI seems... very clunky to use. In my opinion, editing a raw text file seems easier - although you still have to deal with conflicts and missing strings, of course. I could be wrong.

I think the real solution would be to add more automation to the current PR-based translation system. I don't run the bundle update script very often because it causes merge conflicts with older PRs, and removes comments. The issue with conflicts requires some more thought, but comments and spacing can be maintained.

**Comment by jimmy927** [comment]
How about the following ?

I just create a script that translates all untranslated texts with google translate or similar.
That would help a lot with translation-speed and gives almost no additional complexity.

**Comment by ItsJonyBoi** [comment]
Sorry for joining this a little late but, I found something called GitLocalize based on what I read I believe it can help you out. If you want more info here is the link to its Github page https://github.com/marketplace/gitlocalize and also just search about it on the internet and you should find more info.

**Comment by Anuken** [comment]
> I just create a script that translates all untranslated texts with google translate or similar.

That could be integrated into the bundle update script. Instead of copying the english versions of text over, it could copy translated versions.

**Comment by jimmy927** [comment]
> That could be integrated into the bundle update script. Instead of copying the english versions of text over, it could copy translated versions.

Is it ok to do it in python ?

**Comment by YellOw139** [comment]
> That could be integrated into the bundle update script. Instead of copying the english versions of text over, it could copy translated versions.

Unless you find a solution to mark machine translated strings as machine translated in the bundle...
Like, look, there are many bundles which have not been updated in ages which would benefit from this, but a new translator for an old bundle should always know when he should check an entire file for errors and when he should just check strings x and y for errors. English strings in a foreign bundle have a helpful, obvious "Hey, look here, fix me!" which machine translated strings won't have.
Do what works, but for its advantages this solution could also have frustrating disadvantages that would ideally (not necessarily, I agree) be taken care of somehow.
Otherwise I can appreciate how much you care about keeping your game's foreign bundles updated while avoiding conflicts as much as possible.

**Comment by jimmy927** [comment]
> Unless you find a solution to mark machine translated strings as machine translated in the bundle...

Does the current file format support comments ?
Comments on the same line ?

**Comment by ImUrX** [comment]
honestly crowdin would work if it werent for the ios version of mindustry https://crowdin.com/page/open-source-project-setup-request

**Comment by Anuken** [comment]
> if it werent for the ios version of mindustry

...and the Steam version.

> Is it ok to do it in python?

No... every other tool script uses Groovy (in Gradle) or Java, and I don't want to add a dependency on Python.

> Does the current file format support comments ?
Comments on the same line ?

Yes.

**Comment by valtsu41** [comment]
> How about the following ?
> 
> I just create a script that translates all untranslated texts with google translate or similar.
> That would help a lot with translation-speed and gives almost no additional complexity.

In my honest opionion this is a pretty bad idea, because it would probably not give the best first impression from Mindustry. I think it could make Mindustry feel like... a pretty cheaply made ad-filled game. Or a virus/scam. That is what I immediately think when encountering something made with google translate.

**Comment by jimmy927** [comment]
> In my honest opionion this is a pretty bad idea, because it would probably not give the best first impression from Mindustry. I think it could make Mindustry feel like... a pretty cheaply made ad-filled game. Or a virus/scam. That is what I usually immediately think when encountering something made with obvious google translate translation.

I didn't propose the workflow you assume, I didn't envision to translate everything automatically and lust release it without manual QA.

I assumed it would work the following way:

1) run script to replace untranslated texts with translation and mark them as such with comment.
2) correct all translations manually and remove comment
3) create PR

This speeds up translation massively, personally i use google translate even between my 2 mothertongues just because it is such much faster, also google translate has a very good vocabulary even though it sometimes struggles with building basic sentences.

**Comment by jimmy927** [comment]
> In my honest opionion this is a pretty bad idea, because it would probably not give the best first impression from Mindustry. I think it could make Mindustry feel like... a pretty cheaply made ad-filled game. Or a virus/scam. That is what I usually immediately think when encountering something made with obvious google translate translation.

On another note i agree that no translation is better than bad translations.

However translating only parts of the game feels similarly unpolished. Like it is with Swedish right now for example where the game is an obvious mix between english & swedish.

Not sure what then solution is though, but I guess at some point a translation need to be dropped if unmaintained.
In such cases maybe my proposed script would help to make it simpler to maintain a language, especially if you translate to a language that is not your mothertongue.

**Comment by Remint32** [comment]
@jimmy927 In other words, you want to offer your version as a working case when a language has no maintainer for a long time.

**Comment by valtsu41** [comment]
So, the automatic translations would not be released?

**Comment by jimmy927** [comment]
> @jimmy927 In other words, you want to offer your version as a working case when a language has no maintainer for a long time.
> Instead of just dropping it and all the accumulated strings of that language before or leave it as it is.

No, the main idea is to speed up the translation-process.

**Comment by jimmy927** [comment]
> So, the automatic translations would not be released?

Not without a human doing QA on them.

**Comment by summoner001** [comment]
I understand that weblate, crowdin, transifex cannot be used because they cost money to use. But what about gettext .PO files? There is a free solution for that, for example QTLinguist program can open them and the source language and the target language are nicely tracked for the translator. True, downloading the .po files from github and uploading them back after the translation has finished takes more time, but it makes the translation work much easier.

**Comment by Korb** [comment]
This issue proposes integration with a translation platform. A number of tools are proposed, including self-hosted `Weblate`, which is much more convenient than plain text translation simply because it supports a glossary and similar string searches. The issue is closed with the status `Closed`, meaning it's complete. However, neither `README.md` nor `TRANSLATING.md` mentions a translation platform.

Is this an issue with unupdated repository documentation, or is it the fault of someone who didn't close this issue with the status `not planned`?

**Comment by ImUrX** [comment]
There didn't use to be a not planned status for issues 5 years ago.
