### ISSUE TITLE
No sound on linux.

### ISSUE THREAD

**Issue by radistmorse** [Anuken/Mindustry#6349]
I know this was reported several times already, and was always closed as WONTFIX, but the problem won't go away by itself.

In my particular case the problem is with my wireless headset, which doesn't work with pulse-alsa (or rather pipewire-alsa in my case) plugin. God knows why. But this plugin is a compatibility hack designed for legacy software, it was never designed to be reliable, it's just "better than nothing".

You said previously that "audio is just problematic on Linux in general". That's not true. Audio is very simple on linux: you use PulseAudio, and it "just works". Now if for whatever reason you don't want to use PA, that's when it becomes "problematic". I don't know a single major desktop linux distribution that would use raw ALSA without PA (or pipewire, which is the same).

So please, consider supporting PA natively. This problem won't ever go away, and will just become more and more severe as raw ALSA moves deeper into "deprecated" territory.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> So please, consider supporting PA natively.

I would have *liked* to, but PA was broken out of the box for the backends I tried - except instead of "no audio", people reported severe distortion issues. Based on the frequency of those reports, it was far more common than the issue you're reporting, even during the alpha/beta. A few users reported that the problem is fixable via pulseuaudio config manipulation, but "it works, you just have to edit this very specific file" is not an acceptable solution.

I can try updating my audio libraries and hope it was fixed upstream at some point, but if the problem reappears, I'll have to revert back.

**Comment by radistmorse** [comment]
As long as it's a considered option, I'm OK :) Also, you said that using an SDL backend lead to some issues with missing symbols. Wouldn't it be the easiest to fix? SDL was specifically created for games to not deal with all that low-end mess. And you use it for graphics already anyway.

**Comment by Anuken** [comment]
> Wouldn't it be the easiest to fix?

No, SDL is statically linked on windows, and I don't even know where to begin making it work properly when the core shared libraries depend on it.

**Comment by Myridium** [comment]
For those experiencing no sound on Linux, I found the sound to work through PulseAudio immediately after installing `https://archlinux.org/packages/extra/x86_64/pulseaudio-alsa/` (Arch Linux). 

Now @Anuken, there are at least three GitHub issues raised now about sound not working. Why do you keep closing the issue without addressing it? All the other sound on my system works (except for Lightworks which is trash in general; sound device number is hardcoded in a configuration file). Same according to this user. The issue is most likely in your codebase.

It's not a good image to be repeatedly closing a major issue on GitHub (which categorically affects all users of Linux!) because you just don't want to fix it. It is still an open issue, so leave the issue open. That's the way GitHub issues work-- closing them is a declaration that an issue was not an issue in the first place, or that it is fixed, or some other marginal cases. It also makes it confusing for users like myself who come to GitHub to see if I'm the only one having this issue, and see the issue has been 'closed' implying it is fixed. It makes it seem like you don't want to leave any open issues, just for appearance's sake. After all, you are making an active decision to mark issues as 'closed'.

If you want others to contribute to troubleshooting or to submit PR requests then you need to leave the issue open-- otherwise it's an official declaration that it's not an issue anymore.

At the very least, you could create a github issue tag 'wontfix' and explain in detail on the issue (or in this case the README.md because it's such a major issue) why the issue is not going to be fixed, and possible workarounds. Or you could create a tag 'upstream-bug' if you are convinced it's upstream. Basically, any small amount of effort to let users know the actual status of this bug is better than closing issues you just don't want to deal with. 

Case in point: I just took another look at the list of issues. Turns out someone already identified the same solution as me: https://github.com/Anuken/Mindustry/issues/6015. I would have seen that a lot sooner if the issue was correctly marked as OPEN.

Now the reason I am complaining so much is because I _paid_ for this software through Steam where this game is clearly marked as compatible with Linux. You are accepting money for a broken product, which you advertise to be not-broken on Linux.

**Comment by radistmorse** [comment]
>For those experiencing no sound on Linux, I found the sound to work through PulseAudio immediately after installing

Arch is the only major linux distribution I know of, that doesn't provide this (or similar) package by default. This is why the sound mostly works as-is. Maybe some hint for arch-users should be made. But then again, if a person installs arch it is his way of saying "I like spending time screwing with my system". They will figure stuff out on their own :)

Anyway, in my case - it doesn't work. When it comes to wireless/bluetooth/other non-standard audio devices ALSA notoriously sucks.
>Why do you keep closing the issue without addressing it?

I think it's just how the issue workflow is organised here. No point in keeping the issues open when you are basically the only one fixing them. And the issue WAS addressed. Master version of arc was switched to PA. Which, BTW, fixed the issue for me, thanks @Anuken. Hope it will work for other as well, and the change will make it to the release.

**Comment by Anuken** [comment]
> Why do you keep closing the issue without addressing it?

I've already addressed it - but I've also already explained my reasoning [several times.](https://github.com/Anuken/Mindustry/issues/6349#issuecomment-972919298) - using alsa was the less-buggy option.

> The issue is most likely in your codebase.

No, *I did not write the audio libraries I use*, and I did not have the knowledge to fix this myself, as I have already explained. Again, *read my previous comments*.

> which categorically affects all users of Linux!

**No**, it very much does not. In fact, it works fine for *most distros.* (Above: "Arch is the only major linux distribution I know of, that doesn't provide this (or similar) package by default.")

> just don't want to fix it. It is still an open issue, so leave the issue open

The issue tracker is a way for me track bugs that *I* am currently working on. The overwhelming majority of Mindustry development - especially on the technical side - is done by me. If I'm not going to fix it, it is extremely unlikely that anyone else will.

> At the very least, you could create a github issue tag 'wontfix' and explain in detail on the issue

Yes, that's a good point; I should use the tag system more often.

> You are accepting money for a broken product, which you advertise to be not-broken on Linux.

I'm sorry that you feel this way, but it's a serious stretch to call this a "broken product". Sound (again) *does* work correctly on most distros, and it was still very much possible to get it working on others by installing a package. 

It's not a great user experience, and I probably should have made the solution more clear, but at the same time: Messing around with packages and configs to get something working properly should not be a foreign experience to Linux users (*especially* Arch users).
