### ISSUE TITLE
Cross platform mod implementation

### ISSUE THREAD

**Issue by intenscia** [Anuken/Mindustry#637]
Hey Anuke, I saw on your trello you are working on a Steamworks integration.

I wanted to mention the [cross-platform modding SDK](https://mod.io) we have created called mod.io. All our code is [open source and hosted on Github](https://github.com/modio) and functionally our system is identical to Steam Workshop, except it'll work on itch.io and everywhere else you need it to (android, web etc).

If you'd like to chat reach out to hello [aaatttt] mod.io. Cheers!

**Comment by Anuken** [comment]
I've thought about this, and the main issue with it comes down to three things:
1) There are no Java versions of the SDK, and implementing a JNI wrapper would take a lot of effort; certainly more than it would to use, say, Steamworks4J. Further complicating the issue is the fact that I have little experience with C++/Java interop, and what experience I *do* have points to it being a long and arduous process to implement anything but the most basic of functions.
2) I've already implemented Workshop support for Steam, and porting it over would take more time and testing.
3) By expending significant effort to get the workshop working cross-platform, I would be losing potential Steam customers, as one of the attractions of paying for the game at all is that it has Workshop integration, while other (free) platforms don't. I would be spending days or weeks implementing a feature that only harms me in the long run.

**Comment by intenscia** [comment]
Appreciate the response and totally understand. Also for the record mod.io is compatible with Steam and will work for your Steam players in the same way workshop does, you just won't get a workshop page.
