### ISSUE TITLE
#6467 electric boogaloo

### ISSUE THREAD

**Issue by Highfire1** [Anuken/Mindustry#6471]
**Platform**: Windows 10

**Build**: v135

**Issue**: server side and client side unit binding can get out of sync

~~don't mind the audio didnt realize obs was recording that aaa~~

https://user-images.githubusercontent.com/45698812/148565787-124e2395-43dc-47b6-99bc-c7d869d0daab.mp4

https://user-images.githubusercontent.com/45698812/148565347-433c9798-2dc5-4f9d-abba-2a414e5b0cd5.mp4

**Steps to reproduce**: 

1. go on a server
2. create some horizons
3. join/leave the server
4. place a few of the single unit binders
5. check that a few of them are desynced

**Link(s) to mod(s) used**: override-lib / ldb

**Save file**: [bug_save.zip](https://github.com/Anuken/Mindustry/files/7829677/bug_save.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: n/a

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
The problem here is that units don't exist immediately on client connection, so processor will load `@unit` as null in the first frame and loop forever. I've fixed this by sending units as part of the world connection data, but if you really want a robust fix, check `@unit` validity in the loop to break out of it - that code is fundamentally flawed, as it will loop forever if you place it with no units around.
