### ISSUE TITLE
Conveyors unaffected by ODD removal without items inside, affecting unit movement speed.

### ISSUE THREAD

**Issue by nilederg** [Anuken/Mindustry#6534]
**Platform**: *Windows*

**Build**: *Steam 126.3*

**Issue**: *Overdome effect lingers in conveyors (unsure about other blocks) long after the dome is deleted*

**Steps to reproduce**: *Place ODD. Add phase, silicon. Power ODD. Delete ODD. Observe nearby conveyor speed. Helpful to see unit speed when atop a conveyor. Do not place items inside the conveyor.*

**Link(s) to mod(s) used**: *None applicable*

**Save file**: [*]([100.zip](https://github.com/Anuken/Mindustry/files/7940492/100.zip))
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by nilederg** [comment]
ok the save didnt link properly, i'll send it here

**Comment by nilederg** [comment]
[100.zip](https://github.com/Anuken/Mindustry/files/7940499/100.zip)

**Comment by nilederg** [comment]
further testing shows this happens in all saves, and also happens when power is cut to the odd.

**Comment by Anuken** [comment]
This happens because conveyors will "sleep" and stop updating after a while with no items, which means their overdrive state stops counting down. In practice, this is nearly irrelevant, as the conveyors will stop being overdriven as soon as items enter them. Very few people use conveyors for unit transport, especially with "missing" overdrive blocks. 

Changing this behavior would incur a performance penalty regardless of implementation - I won't be fixing this.
