### ISSUE TITLE
Strange bridge conveyor behavior and logic connection order issue

### ISSUE THREAD

**Issue by Hexrotor** [Anuken/Mindustry#6547]
**Platform**: Tested on Android and Windows

**Build**: 22306

**Issue**: 
1. When I was testing my schematic, the bridge conveyor showed a auto connecting behavior at a specific place. Watch this video:

https://user-images.githubusercontent.com/45112661/152002273-25f7b4af-5d78-42de-9bbf-17b78abde360.mp4

2. I placed a logic and connected 5 unloaders, then I disconnected 2 of them, only left `unloader3/4/5`. And I copied them, the connection signs changed to `unloader1/2/3`. Watch this video, it's just a example to explain this issue, you couldn't imagine how painful am I in changing my logic codes 😂

https://user-images.githubusercontent.com/45112661/152009308-256311df-14e6-4e11-8067-f8910f5688a9.mp4

**Steps to reproduce**: Do things like I did in videos.

**Link(s) to mod(s) used**: none

**Save file**: 
Issue1 map save(bro this is not a zip file, i exported it in load game page, mindustry didn't give it a extension):
[bridgebug.zip](https://github.com/Anuken/Mindustry/files/7979946/bridgebug.zip)

issue1 schematic: 
[bug.txt](https://github.com/Hexrotor/Mindustry-Myblueprint/raw/315728b3ef8bd286c72e222d396e9595b01976a6/base64text/beta/dualt5_plus.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
1.

> the bridge conveyor showed a auto connecting behavior

Sorry, but I've fixed so many recurring bugs with bridge auto-connections that I frankly don't care anymore, I'm not touching their behavior, because any bug I "fix" leads to two others.

2.

> And I copied them, the connection signs changed to unloader1/2/3

The reason for this is that the processor is built *first*, *then* the unloaders are placed. When the processor is placed, it doesn't have anything to link to, so all the link names are removed. When the unloaders are found again, they are linked with new names.
