### ISSUE TITLE
iOS TestFlight build has expired

### ISSUE THREAD

**Issue by TheGamer1002** [Anuken/Mindustry#6598]
**Platform**: iOS

**Build**: 135

**Issue**: The latest TestFlight build for Mindustry has expired.

**Steps to reproduce**: Attempt to open latest Mindustry TestFlight build on iOS, and receive a message that the beta has expired.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

(Please don’t reap my soul, I can’t even get into the game.)

**Comment by Anuken** [comment]
Apple doesn't provide a way to "un-expire" builds, and as there's no new build and nothing new to test, I can't do anything about it. Pushing an identical release isn't viable for technical reasons, and I don't think there are any new bugs to discover anyway.

**Comment by keithaw** [comment]
You mentioned yesterday about the save bug: “fixed in private branch - switched to sharing without intermediate files.”  Would that be a small enough change to merge with minimal fuss and keep the TestFlight going?

**Comment by Anuken** [comment]
It's fixed *in the private branch*, which has countless other changes that are not ready for release.

**Comment by keithaw** [comment]
I wasn’t suggesting that you merge the entire private branch, I’m not
daft.  If the save feature is not that easy to break out as a separate
change, I accept that, or if you just don’t want to bother.  But my
suggestion is not as stupid as you choose to make it sound.  I do program
for a living and know it is not anything outside git’s capabilities.

**Comment by Anuken** [comment]
It's not really viable to backport it to `master` either, as the `master` version of Mindustry doesn't support the Arc version I'm using, and considering the two months that have passed since release, there have been numerous changes that may (or may not) be incompatible with the current latest release. In short, I would need to:
- Test all the new changes to make sure they're compatible (or not)
- Resolve the branch spaghetti, find a commit of Arc that still works with Mindustry
- If the changes *aren't* compatible, create an entire new version and announcement that all server owners and players will have to update to

I could also try to resolve this all on the iOS end by getting the last release commit, adding in the fix and attempting an iOS-specific release with that, but it would also require rewriting my build scripts to use different repository versions, as well as fiddling around in my incredibly-slow VM, and frankly, as you said, I just don't want to bother.

**Comment by Anuken** [comment]
...I've thought about it some more, and there's also the option of just attempt to re-upload the old build with a tweaked version number. This is significantly easier than the other options, but doesn't involve any changes. I'll see if it works.

**Comment by TheGamer1002** [comment]
This should work, I’ve seen plenty of “no test notes” in TestFlight.

**Comment by TheGamer1002** [comment]
It works, thank you

**Comment by crash5545** [comment]
This is an issue again. Since the content in Testflight isn’t being brought to the IOS stable release, can the beta be re-upped as suggested in this thread indefinitely until a new release closes the gap?

**Comment by TheGamer1002** [comment]
I can confirm this. I’ve been too busy to test it, but I checked and it has expired.
