### ISSUE TITLE
Enemy stuck off of edge of map

### ISSUE THREAD

**Issue by PaulBags** [Anuken/Mindustry#66]
Used the editor to make an open map with minimal border, and an enemy got stuck off the edge of the map and I couldn't kill it. Some turrets were in range and not targeting it, but it was shooting up stuff just fine. I think it was one of those tank things spawn babies, I suppose it spawned there instead of jumping terrain? It being there didn't hold up the next wave either, counter showed no enemies.

![stuck off edge](https://user-images.githubusercontent.com/19583196/34645942-09e0cdbe-f3c0-11e7-81f0-a71808b32c4e.jpg)

**Comment by Anuken** [comment]
It's possible that if you placed a spawnpoint near the edge of the map, an enemy spawned out of the world, as the enemies spawn within a specific range of each spawnpoint instead of directly on it. Not going to fix the spawning, as this is an issue with a specific custom map, but perhaps enemies will be changed to self-destruct when out of bounds.

**Comment by Anuken** [comment]
Enemy and player positions will now be clamped to fit the map as of a85357d5c619db9c8c2f4a8417ae39e54cacb0b8.
