### ISSUE TITLE
Unloaders speed drop on mass drivers

### ISSUE THREAD

**Issue by MekBoss** [Anuken/Mindustry#6643]
**Platform**: Windows 10

**Build**:  pre alpha 135

**Issue**:  Unloader, if placed near mass driver which receive items by direct contact with other mass driver, unload items with half of its speed. It depending on a position of a belts near it

**Steps to reproduce**: import and build (in sandbox) next schematics.

bXNjaAF4nMWQv2/aQBTHn3+DjUiqGgUy0YGIJDiy+he0GxJtCk2XKELCsU+JI+xzbKDt2rlLBzZG1L+jM6Jqx84RP5Z0yxYk9x2ukfgLcqen73vv7nTf94F9yAkg+pZHoNT3u9RySFh2QneAEgWEOOXL/hVoDons0A16LvUBQO5al6QbAX/RVkBze8QzItoPbQKaZ0WRkbyH7PpkQF0HcgH9SML01o7n2iE1gpDaJIpoCM96bs/y3b5n2NQfkM/YyqRu8L8XGJCVADiOZSpmisAybZ1xwIOqYJlhPY4Haa0gA6/EcWxh/BV4LHEJKHJGBIhX8QrE/5sTROwrebxw82lkO53O9fG7aa1l3h2dGq36aa1VP5zUGsbL2eTop9E0P1RPDidvTm6N2tsp11gOF7OgslwO9fmyOl5UDubj7z8eqsVX5b0/9bPRJPdteP6F2/td+Zq7bxbi2DQFeP3LfI+elMSpCgpzusJ4XJcqK9sYcxxHRdc4k4pGBRlFYiRwZg37eJLfoMlv0OQ3aHa30TxPPtS30egJGj1Fw5CkeBCN/hRoConT4jaa4jaaIgMgo6RMSoyJhCImIoHwD44tx1I=

After building wait 2 seconds for it to sync, to make buggy behavior more clear.
Unloader in a right group of mass drivers behaves as it should, i.e. unload lead as it should.
Unloader in a left group of mass drivers unload lead at half of speed of a right one, despite mass driver have more than enough lead.

**Link(s) to mod(s) used**: none

**Save file**: no

**(Crash) logs**: no

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
@hortiSquash The reason this appears to happen is that mass drivers get a lower load factor than conveyors when the latter have even one item. You can see this by placing a single conveyor with an unloader next to the schematic posted - only one item ever enters the conveyor. Conveyors should always have the lowest unload priority, as they can't ever be unloaded from. In this case, they don't, resulting in the unloader putting items nowhere.

My fix:

![image](https://user-images.githubusercontent.com/10100000/158612956-7830eacc-b893-405c-86a6-ac1ebce92214.png)

Removing the commented out code from the comparator fixes the priority issue, but I don't know why it's there in the first place so I can't say if it will break other schematics.

Let me know if this is a bad idea, I don't have any relevant schematics handy.

**Comment by hortiSquash** [comment]
@Anuken i think this test is quite important but i forgot exactly why

as for the bug itself, its tied to MDs in sending mode being able to both give and recieve with unloaders, and i think that is literally the only block in the entire game that can do that

i have "give priority" for blocks that can give but not recieve, but since MDs can do both, i need to make "recieve priority" for blocks that recieve but not give

i'll investigate tomorrow or this week-end if i can find a way to redo the comparaisons to account for that
if you have any idea let me know, im not in the mindset for comparaisons algebra right now

btw i know you hate schems so here's my barebone version
![image](https://user-images.githubusercontent.com/45213805/158738645-2779cfa5-67d9-48b7-a660-23bedb65635c.png)
