### ISSUE TITLE
block placement on map borders

### ISSUE THREAD

**Issue by hortiSquash** [Anuken/Mindustry#6741]
**Platform**:
Win10-64 but i doubt it matters

**Build**:
22388 and probably way older versions as well

**Issue**:
inconsistency in block placement on borders depending on which side it is, and the size of the block you try to put down
![image](https://user-images.githubusercontent.com/45213805/166104323-7f316b8a-dc96-4e25-874a-0d1c42a35410.png)

(in the map editor, you are allowed to put a block of any size right next to the border, with all sides being the same)

**Steps to reproduce**:
100% reproduceable, just go in any map and place blocks on the world border

**Link(s) to mod(s) used**:
vanilla

**Save file**:
[saves.zip](https://github.com/Anuken/Mindustry/files/8596821/saves.zip)
i linked both map frommap editor and game save from me trying to reproduce it in game

---

- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by hortiSquash** [comment]
it has already been reported two years ago but they didnt talk about the inconsistency depending on which border you try

**Comment by Anuken** [comment]
I've been aware of this for a while, and while the cause is obvious, it's ambiguous as to what the best solution is. What I'll probably do:

- Keep disallowing 1x1 blocks on borders. You can barely see these and there's no good reason to put them in darkness. (The map editor is irrelevant here, it allows you to do all sorts of illegal stuff anyway)
- Add a special case for 2x2 blocks so none of the positions shown are valid for them, regardless of which side of the border they are on.
- Keep everything else the same (it's big enough to not be lost in the fog). Reasoning: It should be invalid if its *center* is in fog, and 3x3+ blocks' centers are not.

**Comment by hortiSquash** [comment]
`block.size / 2f > 1 +`distance(center, border)

![image](https://user-images.githubusercontent.com/45213805/166107483-683c58bc-8aeb-4560-ade0-4e8402a641c1.png)

**Comment by Anuken** [comment]
Yeah I could do that, but the current algorithm uses world darkness, which can be anywhere in the campaign and is calculated per-tile (not per-coordinate).
