### ISSUE TITLE
Erekir branch: crashes are not producing crash logs

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#6764]
**Platform**: *Doors*

**Build**: *"custom"*

**Issue**: *Testing multiple modding API issues and crashing a lot. Never getting any log.*

**Steps to reproduce**: 
1. wait for it to erekir custom build
2. The game will now exit, to reload mods.
3. fuck around

**Link(s) to mod(s) used**: *(is linking the game a valid option?)*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

cant actually provide it lmao the game crashes

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *hmm yeah ill just find those real quick*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have ascended beyond the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
If the build is actually a "custom build", it's not a bug - I disable crash logging for custom builds, because it is assumed that "custom builds" are run through the terminal/command line by developers, and crashes *there* are logged through the console, because it's rather annoying to have logs pop up and get saved *when you're developing something*.

You should either:
- Build the game with a real version `-Pbuildversion=136`
- Run the game through the terminal or IDE so you get the log upon crash
