### ISSUE TITLE
Vurnereble attack 1rst time

### ISSUE THREAD

**Issue by RealWetter** [Anuken/Mindustry#6806]
If you have on your planet map a base next to you and if you capturet it and they base attacks you and you go to another area you will instent lose your fielt even you have 6 forshaduws and 5 spectrus and 3meltdowns and much shielts
And 10 mega's and 10 poly's

**Comment by RealWetter** [comment]
I hope you see this becuz its anoying bug

**Comment by SMOLKEYS** [comment]
no shit i cant understand anything you said

**Comment by SMOLKEYS** [comment]
you also removed the issue template so this is gonna get closed after a bit

**Comment by Mnemotechnician** [comment]
they're complaining that the enemies captured their sector because they did not set up a proper defence

**Comment by SpaceEarthEX** [comment]
not a bug(?)

**Comment by Cerulity64X** [comment]
Go to the attacked base and defend it until the waves are done? You do know how slow the game would be if it simulated every sector, right?

The game does equations when you’re not there to destroy blocks instead of spawning and moving enemies and aiming turrets. These equations are much worse difficulty-wise than an actual simulation, and so you can die when you don’t take care of a vulnerable sector. It’s just Mindustry.
