### ISSUE TITLE
World Processor sync to other player but not server if edited ingame

### ISSUE THREAD

**Issue by Jackson11500** [Anuken/Mindustry#6816]
**Platform**: All

**Build**: Latest BE build

**Issue**: World Processor sync to other player but not server if edited ingame. 

**Steps to reproduce**: if you enable editing world processor ingame, its content would sync to the other players(does not matter if they have enabled edit), force control their view or change something. But this edit would not sync to server, and thus disappear after sync

_By the way, the flush message does not disappear after exiting the map, quite annoying if they print a long message and set time to 99999. This would force you to reopen the game._

**Link(s) to mod(s) used**: use custom client to enable editing world processor ingame, but this would affect all players.

https://user-images.githubusercontent.com/55009845/167771365-a76009d5-5caf-4154-9bea-df75c630169b.mp4

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
> use custom client to enable editing world processor ingame,

You're not supposed to do this. World processors should not be edited in multiplayer and I do not support custom client bugs.

> Build: Latest BE build

"Latest" is not a game version.  The version you might *think* is the latest may not actually be the latest.

> Platform: All

"All" is not a platform. If you are playing on Windows, specify that the platform on Windows.

**Comment by Jackson11500** [comment]
> You're not supposed to do this. World processors should not be edited in multiplayer and I do not support custom client bugs.
>
I meant that, this bug can be edited by anyone who have enable world processor editing, and affact ALL player(the other player maybe of any platform)


> "Latest" is not a game version. The version you might _think_ is the latest may not actually be the latest.
>
In fact this bug is still active.

> "All" is not a platform. If you are playing on Windows, specify that the platform is Windows.

>
Can be done by anyone who enable world processor editing, and affact all the other player. Might be used by hacker

**Comment by Jackson11500** [comment]
the platform is not the key point, editing world processor can be done by custom build client, mod or some other methods. The key is, once you edited it ingame on server, all the other players(regardless of platform or client they used) would be influenced. And print a long flush would block their screen until they restart the game

**Comment by Anuken** [comment]
> In fact this bug is still active.

It doesn't matter, the template asks for *your* version, so provide the version.

> Can be done by anyone who enable world processor editing

Again, doesn't matter, the field is there so I know *which platform you are on*, not what platforms you *think* it occurs on.

> editing world processor can be done by custom build client, mod or some other methods. The key is, once you edited it ingame on server, all the other players(regardless of platform or client they used) would be influenced. And print a long flush would block their screen until they restart the game

But that doesn't make sense. You cannot be affected by this unless the map is already in editor mode (in which case *anyone* can edit processors), or everyone else is running this custom client as well. World processors reject configuration changes outside of the editor *regardless* of who they come from. 

I've tested this in custom maps, and it functions correctly - bypassing world processor edit checks *on one client* and adding a cutscene to the processor does nothing to the server *or other clients*, because they reject the configuration - as expected. You have not specified the map or code you are even running, so I can't test this properly.
