### ISSUE TITLE
[136.1] Fail to join a server with "Unknown Network Error"

### ISSUE THREAD

**Issue by SukkaW** [Anuken/Mindustry#7234]
**Platform**: macOS

**Build**: alpha build 136.1

**Issue**:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/40715044/180637623-6aa9d34d-5c54-4cc6-8014-5d590a6d4aad.png">
<img width="733" alt="image" src="https://user-images.githubusercontent.com/40715044/180637934-4c1516e6-e44a-44d9-85f8-18fd13ab76b0.png">

**Steps to reproduce**: Play -> Join Game -> Click a server -> Loading Map -> Unknown Network Error

**Link(s) to mod(s) used**: I have disabled every mod I have installed and the issue persists.

**Save file**: I have gone to Settings -> Clear Game Data... -> Try joining the server again, no luck. So no.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by end-me-please** [comment]
Likely an issue with the server version

**Comment by Jackson11500** [comment]
Agree, this problems is extremely common on V7 server, especially when a map have lots of players or have played for some times. It seems that join the other server or compaign before join the problem server may resolve this problem temporary.

**Comment by SukkaW** [comment]
> Agree, this problems is extremely common on V7 server, especially when a map have lots of players or have played for some times. It seems that join the other server or compaign before join the problem server may resolve this problem temporary.

By now it is indeed the only workaround. But it should also be only a temporary solution, isn't it? It is definitely not a long-term solution.

**Comment by Anuken** [comment]
Works on my machine. Cannot reproduce.

**Comment by SukkaW** [comment]
> Works on my machine. Cannot reproduce.

Because your machine doesn't have 20 players PvP at the same time.

If you can't build a server to handle multiple players, just do not implement multiplayer.

**Comment by end-me-please** [comment]
Idk about you but I have played multiplayer with 50-60 people on a server before with no problems. 

(other than coordinating all the players, that *is* a problem.)

**Comment by Anuken** [comment]
> If you are not able to build a stable server implementation to handle multiple players, then do not implement any multiplayer at all.

What a truly incredible take. I guess if some random user sees a bug in some feature, I should just delete it, or give up immediately. I guess all the people who are enjoying <20 player games - which is, most of them, probably - can just go screw themselves.

> Mindustry really should improve the Network Stack.

Alright then, let's hear your ideas. What's wrong with my network stack, then?

**Comment by Jackson11500** [comment]
I can confirmed the SukkaW's problem is so common that most of my friends have met this problem, regardless platform(android/steam/pc) or mod or server they used/entered. You have to explain to the players who are new to V7 that enter the compaign or the other server before join the problem servers again and again.
The true problem is that this appears randomly and only at some special situations, while the log reports different errors each time(as shown in #7234 or #7245). For our experiences, the more players and the longer playtimes for a map, this problem is more likely to appear. And once it appear to you, you can no longer join the server before taking the measures above. 
Notable, althought new players cannot join the server, the players in server play normally.

**Comment by SukkaW** [comment]
> I can confirmed the SukkaW's problem is so common that most of my friends have met this problem, regardless platform(android/steam/pc) or mod or server they used/entered. You have to explain to the players who are new to V7 that enter the compaign or the other server before join the problem servers again and again. The true problem is that this appears randomly and only at some special situations, while the log reports different errors each time(as shown in #7234 or #7245). For our experiences, the more players and the longer playtimes for a map, this problem is more likely to appear. And once it appear to you, you can no longer join the server before taking the measures above. Notable, althought new players cannot join the server, the players in server play normally.

I am afraid Anuken just does not have the ability to solve the issue, as well as the ability to implement a proper error logging under such cases. And since he doesn't have the ability to fix the issue, he just uses some random excuses like "no log provided" or "server-side mod" (even if the issue occurs on a vanilla server/client) or "can't reproduce on my machine", and insist to publishing defected software.

**Comment by Anuken** [comment]
> while pretending he is such a strong developer

And where, exactly, have I ever even claimed to be a "strong" developer at all? *Nowhere.*

> or "can't reproduce on my machine" to close the issue

And how, exactly, am I supposed to fix an issue *that doesn't happen to me?* Have you ever tried to solve an issue like this in *
*your own game?* Do you even know how Mindustry's ""network stack"" works?

> and insist to publishing defected software.

...For free, with its source code readily available. What a crime. What a horrible thing to do.

The amount of entitlement I am seeing from you right now, is quite frankly, *staggering*. You come into a repository for my *freely available* game, you call me incompetent, you make up a load of nonsense about me claiming things I never have, and you demand changes, because... I owe you something?

...But guess what, **I don't**. You are free to not use this software at all. Demanding fixes gets you *nothing*. I see you complement ignored my last question - because you do not have the slightest clue of what you are talking about here; *stop acting like you do.* 

(Blocked from this repo.)
