### ISSUE TITLE
Game freezes when Poly try help me

### ISSUE THREAD

**Issue by Fl414r** [Anuken/Mindustry#7257]
**Platform**: *Android*

**Build**: *22902*

**Issue**: *Game freezes when Poly try help me. 
upd. The bug seems to require a special situation, now I can't reproduce it...
upd 2. https://youtu.be/TQ6S15mFlxc (sounds not captured, but they looped)*

**Steps to reproduce**: *Start dismantle something in Serpulo 47 sector and wait before Poly try help.*

**Link(s) to mod(s) used**: *Developer Mode (https://github.com/deltanedas/dev-mode), Informatis (https://github.com/Sharlottes/Informatis), Time Control (https://github.com/sk7725/TimeControl), UI Lib (https://github.com/deltanedas/ui-lib)*

**Save file**: *https://drive.google.com/file/d/1X-r5mocoWviE-42gD-mXXL91KNkuEWWC/view?usp=sharing*

**(Crash) logs**: *Freeze not create crash log*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
***(But problem ignored)***

**Comment by Fl414r** [comment]
Here I catch this bug in 80% of attempts
https://youtu.be/NXeTVDFZBoY

**Comment by Fl414r** [comment]
22903 same

**Comment by Anuken** [comment]
Here is what I tried:

- Downloading the save, deconstructing on that sector on PC. Several attempts, clean saves.
- Launching the game on a real Android phone, using that specific save, following the exact actions. Restarting the game, tabbing out. Multiple re-tries.

None of these things lead to a freeze. You have multiple significant mods installed, at least one of which has caused serious crashes in the past. While you are not the first person to report this, I am still completely unable to reproduce it.

It could be caused by:

- Something specific to Android devices
- Something specific to your mods

Nothing looks wrong in the building code; I will need to wait for more reports to come in to make sure that this is not an Android device-specific or mod-specific bug.
