### ISSUE TITLE
Sorter build between junctions clogs randomly

### ISSUE THREAD

**Issue by ShadowsInRain** [Anuken/Mindustry#760]
**Platform**: Windows (10)
**Build**: Steam build 96

**Issue**: Sorter clogs, if it's input and discard both attached to junctions.

**Steps to reproduce**: Picture, top: what I am trying to do. Picture, bottom: minimal working example.

![image](https://user-images.githubusercontent.com/1629574/66013012-00953b80-e4e3-11e9-93fc-2f6b0dec5f7d.png)

Both junctions must be present, replacing either one fixes problem. Placing junction on filtered output has no effect. Rebuilding (part or whole) has no effect, same with building order.

**Discussion.** I wonder why sorters made with inverted logic. Filtering selected items to the side would make sorting trivial.

**Comment by Anuken** [comment]
Three "instant transfer" blocks, like junctions/sorters, cannot be chained in a row, to prevent infinte loops. While junctions are technically not instant, their checks for acceptibility are/were. That's why your design breaks. It's not a bug, although whether it is the best solution to the infinite-loop problem is another matter.
