### ISSUE TITLE
all map under attack

### ISSUE THREAD

**Issue by Milkah59** [Anuken/Mindustry#7721]
**Platform**: `Windows 10 x64`

**Build**: `steam build 126.3`

**Issue**: *all my planets are under enemy attack, I lost all my research*

**Steps to reproduce**: *nothing*

**Link(s) to mod(s) used**: `none`

![20221015100439_1](https://user-images.githubusercontent.com/115866777/195988139-88acc83e-5868-4eee-b21c-d688d1ccafb9.jpg)
![20221015150732_1](https://user-images.githubusercontent.com/115866777/195988145-2312d8b4-a7ff-48f7-9024-ff8a1edb079f.jpg)
![20221015094909_1](https://user-images.githubusercontent.com/115866777/195988161-c3f6af27-7bbf-4410-9208-278bffad5942.jpg)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by FrancisP100** [comment]
My mindustry game already had that  issue🛠
In my case it happens when i´m playing and the pc turn off in the middle of game
All planets under attack ,research tree restarted and all sectors progress losted
I didn't find a way to have my progress back
But if you already have exported your mindustry data before
You just have to import your data ✌
Happily i had an exported file and just imported it😉

**Comment by Anuken** [comment]
126.3 is not the latest version, and this has been reported countless times.

**Comment by Milkah59** [comment]
I have the latest update, I didn't see the first line of the topic.
how do you fix the problem without restarting the game?

**Comment by Anuken** [comment]
The problem cannot be fixed. 126 is more than a year old, the latest version is the beta.

**Comment by Milkah59** [comment]
Ok thank you for the answer..
