### ISSUE TITLE
um

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#7733]
**Platform**: *doors*

**Build**: *"latest"*
**Issue**: *i think you forgot some blending if statements (junction interaction, top left)*
![image](https://user-images.githubusercontent.com/61173114/196061309-c8d278f0-ac89-49df-af85-df44d40eb686.png)

**Steps to reproduce**: *.*

**Link(s) to mod(s) used**: *.*

**Save file**: *[lel](https://github.com/Anuken/Mindustry/files/9795815/sector-erekir-58.zip)*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
can you seriously stop trying to be funny in these issues? it's not helpful at all to see titles like "uh", randomly omitted fields or other issues that don't properly describe the problem, I'm not checking github to have a laugh here. it's just annoying. if it's minor and you can't be bothered to put together a proper issue, I'd rather you even PM me

**Comment by BlueWolf3682** [comment]
the fuck do you expect me to do??? the modded mesh crash was happening for *months*, and i notified you of it *multiple damn times* out of github
second, you expect to just know the entire issue by its title? i dont, and i always go to read it 
third, i dunno man it seems really obvious how to reproduce it, and sometimes the info doesnt affect anything - i will *always* make sure i am up to date with the most recent commit before submitting a bug report, and i tested to make sure this was a vanilla problem
im sorry if you dont actually take action until i put a big banner on it, i dont like making obvious bug reports for little things either but ive gotten sick of nothing happening when i ping you mutliple times over this issue and get absolutely nothing.
my bug reports look like jokes because i hate sounding technical and they give all the required info - in reality, i *make sure* to double and triple check and even quadruple check, even sometimes with my mobile client, that they are bugs.

**Comment by Anuken** [comment]
> the fuck do you expect me to do

write "conduit blending incorrect" in the issue title. literally anything to do with the problem, even. not a random word.

> the modded mesh crash was happening for months, and i notified you of it multiple damn times out of github

where was this exactly? I see no mention of it in PM, and if you mean "randomly pinging me in the modding channel", then, no, that's not how you should report issues. I'm not going to read through message history and unrelated conversation to try and fix something that may or may not be a bug. you have no idea how annoying it is to get a random ping with 0-2 words of context and then have to try and piece together whatever the heck you're trying to tell me.

 **I'm not even reading anything on the server anymore.** at all. I don't want to be there anymore. And as mentioned in the rules, you shouldn't even ping me for that. if you want it fixed, report it properly here or at least send a PM, it's not hard.

> third, i dunno man it seems really obvious how to reproduce it, and sometimes the info doesnt affect anything - i will always make sure i am up to date with the most recent commit before submitting a bug report, and i tested to make sure this was a vanilla problem

is it really that hard to just type "windows" instead of some random irrelevant word? I don't care if you think it's irrelevant, it takes you less than a second to type, and if by some slim chance I *can't* reproduce it, it can't *hurt*, right?
