### ISSUE TITLE
Overflow conveyors sometimes divert resources on a fully compressed but moving belt

### ISSUE THREAD

**Issue by Prezombie** [Anuken/Mindustry#776]
**Platform**: Windows

**Build**: Steam v96

**Issue**: I had a fully filled line of copper going to the core, and set up an overflow belt running to a launch pad. about every 5th piece got diverted to the side belt, leaving gaps in the main output line. I think there's some error in how the overflow block is checking for space in the line ahead, when it should only ever be diverting resources if the line ahead is blocked _and stationary._

**Comment by Anuken** [comment]
I'm not sure if this is really a bug. If the conveyor belt is full, then the overflow gate can't pass any items forward, regardless of whether the conveyor is stationary or not. What if it's trying to pass an item to a conveyor from the side? It may be unable to do so, but the conveyor is technically *not* stationary, as more items can be accepted from the back, and it is still moving. 

The real issue here is that items don't move at perfectly consistent speeds across conveyors, which leads to occasional 'overflow'. Unfortunately, there isn't a viable fix for that.

**Comment by JacksonKearl** [comment]
@Anuken, do the overflow gates have any sort of “debounce”? Such that if the output is momentarily blocked it will wait a bit for output to open before switching to overflow mode?

**Comment by serdarakkilic** [comment]
> @Anuken, do the overflow gates have any sort of “debounce”? Such that if the output is momentarily blocked it will wait a bit for output to open before switching to overflow mode?

This will slow down item transportation dramatically. Each overflow gate you add to the setup will even slow down the transportation/distribution more.

**Comment by albert-92** [comment]
**Platform**: `Windows 10 x64`

**Build**: `steam build 121.4`

The problem depicted by https://github.com/Anuken/Mindustry/issues/776#issuecomment-576293101 is still existent in the newest steam build.

**Comment by Anuken** [comment]
It won't ever be fixed.
