### ISSUE TITLE
Material source not working anymore - Addition to issue #7816

### ISSUE THREAD

**Issue by Cookiemagination** [Anuken/Mindustry#7817]
First and foremost: It would be very kind to not close an issue right away, without even asking a question if something is unclear! Sorry but that is just plain rude and I just want to help find out any bugs / improving the game...

Anyway what I forgot to mention in the last incident, that I was of course not in the map editor itself. I started there but then chose the option "edit ingame", so the blocks do update (as far as I know, because it worked in older versions).

About the save file, if you tell me how to get it, I glady deliver one to you. Because in this map editor-ingame..uh...world there is only the button to leave, instead of saving and leaving. Even in the save files there are only my save files from the campaign, so I don't think there is a way to save. But just like I said, if there indeed is, please tell me and I deliver the file.

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

So if there is still anything unclear just ask me and I provide as much information as I can!

**Comment by Anuken** [comment]
I immediately close issues that do not fit the template. I think I make it *extremely* clear what is required, and that you shouldn't open issues at all if you do not meet those requirements. You are not running the latest version of the game, either (did you click https://github.com/Anuken/Mindustry/releases? because if so, you would see that the version on the top is **not** 126).

> but then chose the option "edit ingame", so the blocks do update

No, *they don't.* It's still inside the editor. This is not a bug.
