### ISSUE TITLE
surge on 175 thorium on stained mountains.

### ISSUE THREAD

**Issue by adamlolgaming** [Anuken/Mindustry#7900]
**Platform**: linux mint

**Build**: 140.3
**Issue**: after researching thorium/surge you can get the material in serpulo campaign without getting it there by deconstructing derelict buildings (vaults and surge towers) 

**Steps to reproduce**: step 1: get thorium in erekir. step 2: deconstruct a derelict vault in (a sector with a derelict vault, for example stained mountains) step 3: profit

**Link(s) to mod(s) used**: vanlilia

**Save file**: i do not have a save file, i tested this bug on multiple machines and it works, 

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by laserman367** [comment]
I don't know if this should be considered a bug. It's what you expect to happen, no?

You can for example also get phase fabric on erekir early by deconstructing specific things (the Smite turrets on crossroads for example), it's VERY minor there because you unlock the synthesizer when you land on the next planet but hey

**Comment by Calreiboz** [comment]
possibly intended

**Comment by Anuken** [comment]
Not a bug.
