### ISSUE TITLE
Block status not correctly reflecting liquid satisfaction

### ISSUE THREAD

**Issue by Yo0o0o** [Anuken/Mindustry#7908]
**Platform**: Windows
**Build**: 140.3
**Issue**:  Whenever blocks that require liquids to work, like plastanium compressor/cryofluid mixer/ cultivator are **directly** touching the liquid generator (oilex/wext/pump) the block status does not accurately reflect liquid satisfaction.

Below I attached two gifs to compare block status representation:
https://gifyu.com/image/SEoAP
https://gifyu.com/image/SEoAe

**Steps to reproduce**:Build this setup and watch it not flicker.
**Link(s) to mod(s) used**: none
**Save file**: [BlockStatusBug.zip](https://github.com/Anuken/Mindustry/files/9997282/BlockStatusBug.zip)
**(Crash) logs**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment]
It's hard to define which one is wrong here. In the first one, the mixers are *technically* operational, they just aren't getting "enough" water for full efficiency, just like with 50% power, so they are green.

In the second, the liquid system is pretty broken, so they flash because they are getting uneven amounts of water every frame. This may be "fixed" to be the same as case 1, if the liquid system ever gets a rework. But for now, it will remain as is.

**Comment by hortiSquash** [comment]
> the mixers are _technically_ operational, they just aren't getting "enough" water for full efficiency, just like with 50% power, so they are green.

1 - so why is the water icon on the block info blinking? different check?
2 - if that doesnt work, maybe make the status rhombus be red if under a certain efficiency like 5-10% ?

**Comment by hortiSquash** [comment]
@Anuken how do you explain the water extractor being **full** yet its status is red and not orange?
![image](https://user-images.githubusercontent.com/45213805/202318519-b452ad08-b63c-47bd-8adf-459deea92286.png)
