### ISSUE TITLE
Frequent Crashes on My Ancient Android

### ISSUE THREAD

**Issue by LeahLuong** [Anuken/Mindustry#8016]
**Platform**: Android

**Build**: 140.4, updated from Play Store recently.

**Issue**: See title. I think it's a hardware issue but the Play Store says my phone should be compatible. Been playing on & off for years, same device, & the issue seems worse now.

**Steps to reproduce**: I'm unsure but it happens seemingly every few mins, sometimes when the game is booting up. I think it may be an issue w/ RAM. The game sometimes loses progress after crashing, resulting in the loss of resources or even acting like I abandoned a sector (not even preserving phantom bldg's when I launch there again).

**Link(s) to mod(s) used**: N/A

**Save file**: Please don't reap my soul. IDK how to upload a save & am unsure it would help if this is indeed on my end.

**(Crash) logs**: I was unable to find that but maybe this last_log.txt will do:

[I] [GL] Version: GLES 3.0.0 / Qualcomm / Adreno (TM) 308
[I] [GL] Max texture size: 4096
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [ANDROID] API level: 23
[I] [RAM] Available: 192.0 MB
[I] [Mindustry] Version: 140.4
[I] Total time to load: 14546ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 27 community servers.
[I] [AndroidGraphics] [destroy]

My phone's model (ZTE Z833) allegedly has 1 GB RAM but this .txt seems to think otherwise. Do I need to update OpenGL?? If so, how?? Are there settings I can adjust to improve performance??

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment]
its a RAM issue - unfortunately, the only thing you can do is get a new phone. 
~~and yeah you probably should if it takes 15 seconds to just load the basegame~~

**Comment by Splarkszter** [comment]
It's quite obvious. Probably making an issue while knowing what's the solution is a bit unnecessary.

1GB of total RAM, 8GB of SD storage, Android 6.

Your only solution is to buy a new phone. Lmao | It's not expensive, on ebay i've seen many Galaxy S9 at 100-150$ USD.

If you need no more help, please close this issue.

**Comment by LeahLuong** [comment]
@Splarkszter I think you're wrong about sysreqs. Steam lists it as 1 GB RAM, 200 MB storage, OpenGL 2.0. I'm running Android 6.0.1, have more than the requested storage, & my phone is listed online as having the minimum RAM.

As I mentioned previously, I've played this game for some time. I had a full clear of every sector on Serpulo before wiping game data for v7. The problem w/ crashes existed in prior versions but wasn't as bad as it is now.

When I pull up memory usage in my phone's settings, it says Mindustry is using 62 MB right now. This is well below the seeming 192 MB it thinks it has. I've tried to minimize graphics settings & I play w/ all the sound sliders on the left. Is there something more I can do to make it so the game isn't crashing every few mins, like it was in v6 & prior??

**Comment by Splarkszter** [comment]
> I think you're wrong about sysreqs. 

I didn't list syst req, it's what google spit up when searching your phone model.

I had a Samsung Galaxy Prime, that crap lagged a lot and became super slow. Due to it having 1GB of RAM, and i'm pretty sure same happens to you.

Also never trust what android tells you. Android has a task scheduler that puts to sleep every app as soon as you leave them(specially with such low RAM capacity), as soon as you leave the app it sends it to a swap cache on the SD Storage.

Since v7 has more content it has to load more assets but your phone can't handle them because the RAM fills up. Me on my PC a normal world it takes 600MB of RAM alone.

There's nothing you can do, you don't have the hardware to run the game, upgrade or else. It's just how it is.

**Comment by LeahLuong** [comment]
I appreciate the time you've taken to address my issue. Thanks for that.

This issue isn't simply confined to my situation if what you say is true. The Play Store says Mindustry is compatible w/ my system. I meet minimum sysreqs according to Steam. I've been able to play the game in the past w/ infrequent crashes.  Now, the game is crashing quite frequently & losing progress I make when I am able to play. I think Anuken may need to update the minimum reqs for this game @ various outlets if those stated are insufficient to run it.

**Comment by Splarkszter** [comment]
Yeah, world still goes foward, Tech always improves and computing power is ever more hungry and hungrier.

That's why when people build desktops we usually date a life expectancy, not because the PC may break but because if you want to run the latest and greatest the hardware may not be enough to play at acceptable framerates.

There's always a path, as i said, i've seen cheap high-end phones on the used market, if your budget is constrained always search on the used market, planned obsolescence is a thing but that doesn't mean that obsolescence in a practical sense isn't true.

Choose at least 4GB of RAM. I personally use a Galaxy S9 and for what i use it is more than enough, i wont replace it until it dies (or something cheap and way better for my use cases comes along).

**Comment by LeahLuong** [comment]
I thought I'd try reinstalling in an attempt to address this issue & noticed some peculiarities.

Firstly, the app was telling my system it was taking up 479 MB storage before uninstalling. After installing from itch.io, the app is only using 85.1 MB. I'd originally used the Play Store to update my previous game to v7.

Secondly, the new installation retained all my settings, campaign progress, & schematics. I'd backed up my save & schem folders anticipating I'd need to populate the freshly installed 1's but there was no need. How did those files survive uninstallation & then a fresh install from itch.io??

Thirdly, the new installation generated a crash folder when the old issue reared its head again. This is something the Play Store version has never done, in this version or any prior. Following is a copy/paste of the .txt I found in that folder; please let me know if this sheds any more light on this issue:

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 140.4
OS: Linux xnull (armv7l)
Android API level: 23
Java Version: 0
Runtime Available Memory: 192mb
Cores: 4
Mods: none (vanilla)

> Timeout: 'android.content.res.AssetManager$AssetInputStream.finalize() timed out after 10 seconds'
AssetManager$AssetInputStream.close: 565
AssetManager$AssetInputStream.finalize: 598
Daemons$FinalizerDaemon.doFinalize: 202
Daemons$FinalizerDaemon.run: 185
Thread.run: 818

**Comment by Anuken** [comment]
You need a better device.
