### ISSUE TITLE
HTML5 Websocket WSS support

### ISSUE THREAD

**Issue by Anuken** [Anuken/Mindustry#81]
Currently, Multiplayer in HTML5 seems to be completely functional, except that hosting the game on an HTTPS site (like itch.io) fails, as it requires wss. I have no experience with certificates or HTTPS, and thus have no idea how wss support should be implemented, or whether it can be feasibly done at all. Googling for answers has proven inconclusive. For now, I'll have to disable multiplayer for web.

Java websocket library entry on wss: [Link](https://github.com/TooTallNate/Java-WebSocket#wss-support)
Source file with websocket server code: [Link](https://github.com/Anuken/Mindustry/blob/master/kryonet/src/io/anuke/kryonet/KryoServer.java)

**Comment by simonmeusel** [comment]
Im certainly not an expert on this topic, but when you want to create a certificate, there are two options:

1. Self signed
2. Signed by CA

Creating a self signed certificate is easy and *free*, but obviously, because everyone could create one for any domain, your browser does not trust self signed certs. You can manually add a self signed cert to your browser, and it will then by trusted by the browser.

The other option is to create a certificate signed by a CA, which used to cost a lot of money, every year. But nowadays there is a free option used widely: https://letsencrypt.org/. You can basicly create a cert specifically for your domain (I don't know if it works for just IPs). But still you need to keep it up to date. More info at https://letsencrypt.org/

On how to add the cert to the java server, I don't know.

Note: When I visit the url in the iframe, I can simply use http, and then non secure websockets should work: http://v6p9d9t4.ssl.hwcdn.net/html/737219/index.html

**Comment by Anuken** [comment]
From what I can tell, it seems very difficult (or impossible) to set up a certificate that works for any IP, so instead I'm going to add a link on the itch.io page directly to the iframe URL, for people who want to play multiplayer. It seems to work fine that way, as you said. Thanks!

**Comment by simonmeusel** [comment]
Actually, creating a *valid* certificate for every ip, is impossible (or if you could, you could take over almost every website). It may be possible to create a *invalid* one, which users would need to add to their browser, but that's not the way to go (in my opinion)

**Comment by HelloKitty** [comment]
Most browsers default behavior is to reject self-signed certificates too. Especially Chrome.

**Comment by Quezler** [comment]
_resurrection_
