### ISSUE TITLE
End User License Agreement

### ISSUE THREAD

**Issue by DE3000** [Anuken/Mindustry#813]
The code currently has a license but no license exists for playing the game. I don't believe these are the same.

EULA would limit liability for users who play modded versions of the game. Unsafe code execution is one of your concerns so I think you should limit your liability with regards to clients playing modded versions of the game.

Have a look at the [Minecraft EULA](https://account.mojang.com/documents/minecraft_eula#using-our-game) to see how they handle it.

**Comment by Kieaer** [comment]
The game has a modded client (Crystial mod/Desktop's mod and more..) that makes the game more fun.

**Comment by DE3000** [comment]
> The game has a modded client (Crystial mod/Desktop's mod and more..) that makes the game more fun.

@Kieaer - This isn't about making mods its about limiting liability when clients use mods.

Rimworld also talks about mods in their [EULA](https://rimworldgame.com/eula/)

**Comment by Anuken** [comment]
> Unsafe code execution

I don't need to worry about this until code mods become publicly available. For the client, at least, they won't be for a while.

**Comment by Ansraer** [comment]
While I haven't published anything yet (and don't necessarily intend to) I have already written multiple small mods that manipulate the game's bytecode on the fly. 

While I will probably end up creating PRs for any actually useful changes I make (I didn't know that the game's source could be found on github until five minutes ago. Would have saved me a lot of time if I had figured that out sooner) I'd imagine that other modders have made similar progress and might want to publish their stuff as a separate mod. So code mods might be a lot closer than you think.
Heck, all it takes is someone who spends an afternoon porting fabric and the floodgates are open. I would recommend you look into getting an EULA sooner rather than later.

**Comment by Anuken** [comment]
But those would be completely different versions of the game, downloaded from other sources and not loaded into the main game I am distributing. I don't see how I would be liable for something like that, even without an EULA. If someone downloads a fork, are they really using my version game anymore?

**Comment by Ansraer** [comment]
Nah, I am not compiling my own version of the game. I use bytecode injection to add my code to the jar at runtime.
I didn't even realize that you had the source code on github until today. Would have made things a lot easier.

I can't remember the exact circumstances, but I do know that Mojang had to change Minecraft's EULA early on to make it clear that mods have nothing to do with them and that they are not liable for any damage caused.
Plus what happens if someone uses your official json based system to add illegal content to your game?

**Comment by iczero** [comment]
disclaimer: I am not a lawyer and I do not represent Anuke in any way

Mindustry is licensed under GPLv3 (https://github.com/Anuken/Mindustry/blob/master/LICENSE), which is the license for both the source code and the binary game release. The GPLv3 is an open source license, which is almost the polar opposite of an EULA. While an EULA takes away rights of the user (can't reverse engineer, can't distribute assets, etc), an open source license gives you the rights to have and distribute the source. Aforementioned problems about liability are prevented by the GPLv3 already, and given the nature of the license, any mods that are distributed must also be licensed under the GPLv3 and release their source code.

The concept of "adding illegal content to the game" is invalid. A mod that adds content to the game is property of the owner. Content does not magically become part of the game itself; the content is part of the mod.

Code mods already exist as forks of the base game. In fact, there are already several such mods that exist. I have seen no problems stemming from the existence of these mods and I do not see any reason as to why such problems would exist in the future.

p.s. liability disclaimer here https://github.com/Anuken/Mindustry/blob/master/LICENSE#L589-L610

**Comment by Anuken** [comment]
Closing, will reopen if someone comes up with a very good reason to proceed with adding a EULA.

**Comment by vatterspun** [comment]
I know this issue is closed, just wanted to share some possible resources:

* In discussions with a real software licensing lawyer (which I am not), whatever license you choose, please make sure it talks about patents.  That's a huge issue in software development and only getting bigger.

* Whomever authored the code is welcome to license the code and change the license to whatever they wish so you don't need to make a decision immediately.  Numberous projects have started out with one license and then changed direction.  Keep in mind that, as the project goes along, someone might contribute code and not want to change the license.

* There are limitations of liability written into the GPL that appear to cover mods: "... any other party who modifies and/or conveys the program as permitted above, be liable to you for damages" (https://www.gnu.org/licenses/gpl-3.0.en.html ... section 16 in all caps).

* Doom's source code has notably been GPL since 1997 and has a huge number of mods https://doom.fandom.com/wiki/Doom_source_code 

* A project similar to yours that I tracked own makes allowances for mods: Micecraft forge: https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/LICENSE.txt ... note that the author went with the AGPL + some notes in addition to the license - I have no idea how legally binding those are.  

Finally, thanks for spending time and consideration on licensing.  It's usually the least fun part of software development, but programs that address this seem to stick around.  There's a good amount of open code that was written 30 years ago and is still in general use.
