### ISSUE TITLE
Exploit possible on Peaks campaign map

### ISSUE THREAD

**Issue by Larofeticus** [Anuken/Mindustry#8149]
**Platform**: Windows

**Build**: 140.4 distributed by steam

**Issue** and **Steps to reproduce**: 

The first map objective is "Move into core: 50 Tungsten." It is clear that the map intent is to have this objective occur before progression to obtaining Averts, then the RTS AI commences after the 3 minute grace period.

If a player ship manually deposits tungsten into the core, then it does not count towards the map objective. In this way a player can choose to only manually deposit tungsten, develop their economy, and amass a full flight of Averts before the fence to the NPC base is dropped. 

Then, activate the trigger on purpose and fly the averts to destroy both NPC cores with no unit resistance before even the 3 minute grace period expires. The NPC turrets don't even fire more than a few shots because they only start mining and loading ammunition when the NPC base is activated at the 5th objective.

The fix to this exploit would be to ensure that player manually depositing resources counts towards a "Core Item" type objective.

**Save file**: Save fill in a following comment, as it's on a different machine.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Larofeticus** [comment]
[bug_report_peaks.zip](https://github.com/Anuken/Mindustry/files/10388516/bug_report_peaks.zip)

**Comment by Anuken** [comment]
Peaks is mostly a tutorial map; it is not supposed to present much of a challenge. The only purpose of it is to teach how certain blocks can be used. If you have the foresight to intentionally exploit it to be even easier... I don't see that as much of a problem.

> The fix to this exploit would be to ensure that player manually depositing resources counts towards a "Core Item" type objective.

The "core item" objective should **not** take into account player deposits, as other maps (Onset) specifically need the player to move items into the core with ducts instead of mining/depositing them to demonstrate game features.

Additionally, players can also deposit items into the core **multiple times**. What does it mean to deposit 50 tungsten into the core when you can take it out and put it back in? There's already more  than 50 tungsten in the core to begin with.
