### ISSUE TITLE
Controls: can't use alphabetic keys.

### ISSUE THREAD

**Issue by ftvkyo** [Anuken/Mindustry#826]
**Platform**: Linux

**Build**: steam build 96

**Issue**:
When I try to rebind controls, I can't use any of alphabetic keys. When I try, It appears as "Unknown" and does not work in game.

**Steps to reproduce**:
1. Open Controls settings.
2. Click "Rebind".
3. Press any alphabetic key.

![image](https://user-images.githubusercontent.com/17923271/66722821-ba14da80-ee1a-11e9-8f64-ad538e6a159c.png)

**Additional info**:
OS: Arch Linux (latest).
Current keyboard layout: us.
Xorg configuration for keyboard:
```
Section "InputClass"
    Identifier "keyboard defaults"
    MatchIsKeyboard   "on"

    Option "XkbLayout" "us,ru"
    Option "XkbVariant" ",unipunct"
    Option "XKbOptions" "grp:caps_toggle,lv3:ralt_switch"
EndSection
```

**Comment by CA6** [comment]
this is not just a linux issue on android  (chrome book) and go to change the binds shift alt and ctrl show up as unkown as well and binds that were prevously a mouse one are broken if rebound

**Comment by Anuken** [comment]
You can only use the english keyboard layout for rebinding controls.

**Comment by ftvkyo** [comment]
Hi @Anuken.
> You can only use the english keyboard layout for rebinding controls.
Current keyboard layout - "us", isn't it English?

**Comment by Anuken** [comment]
I see "ru" written right next to "us", which is probably what is causing the issue.

**Comment by ftvkyo** [comment]
Ok, I'll check it.

**Comment by ftvkyo** [comment]
After `setxkbmap us` the game and controls worked fine.
But I think that it is still an issue.
A lot of people use more than one keyboard layout.

There are two common ways of implementing user keyboard input:
1. Work with physical keypress events
2. Work with character that program receives

Good example of the first way is GLFW library. If we write
```kotlin
if (key == GLFW_KEY_S && action == GLFW_RELEASE) {
    println("S pressed")
}
```
then "S pressed" will be printed when I press the physical S button, **independent** from my current keyboard layout and from my list of available keyboard layouts. And even if I remap my keyboard layout to emit "B" character when I press "S" button, "S pressed" text will still be printed when I push the "S" button. And when I switch to other keyboard layout (for example, "ru"), pressing the "S" button (which is mapped to character "ы" in Russian layout) will still print "S pressed".
This way is really cool when people have usual physical keyboards with multiple layouts or custom software redefined buttons.

Example of second way is usual console applications. They receive characters generated according to current keyboard layout, so if we remap the "S" button to emit "B" character, these apps will receive "B". And when we switch to other keyboard layout, the characters that application receive change.
It is (IMHO) strange when people use this way when they can use the first one.

But, in this project, some third way is used.
It somehow stops working when available layouts contains unsupported layouts even if the current active layout is supported "us".

--
Sorry if my language is not very good :)
Also I should mention that everything above is just my point of view and I could be wrong.
Feel free to request additional info or if I should perform additional checks.

**Comment by Anuken** [comment]
> some third way is used.
I use SDL's virtual keycodes, which I asssumed would work like the second method you mentioned. Normally, switching to scancodes wouldn't be too hard, but I need to recompile the SDL natives for that, and it's a very lengthy process to set that up on a new computer...

**Comment by ftvkyo** [comment]
Oh, I understand :(
It's interesting anyway, why it stops working, I'll try to investigate this problem.

**Comment by Self-Perfection** [comment]
I have this issue as well.

Build: 96 (built [from AUR](https://aur.archlinux.org/packages/mindustry/))
OS: Arch linux
Configured keyboard layouts: us,ru
DE: KDE

I have additional observations.

First of all, recognition of WASD depends on active layout at the moment mindustry is started. If active layout was us - movement with WASD works. Otherwise WASD does not recognized and switching layout while the game is running does not help. Only keypresses with letters seems to be affected, e.g. "Esc" and "space" always works.

Active layout at startup is a bit tricky thing and took me a while to figure out. A have "per application" switching policy, so active layout for different applications might be different. And that leads to confusing scenario:
1. Let's say I have active window with Firefox and active "ru" layout
2. I'd like to play mindustry and open launch menu to start it. Plasma (process that is responsible for showing launcher menu) is another app and usually have "us" as active layout
3. Before clicking mindustry icon I peek at active keyboard indicator. It shows "us". So everything seems fine and I click mindustry icon.
4. Launcher menu got its input and disappears. Focus returns to previously active window - that was Firefox window. Keyboard layout briefly switches to "ru" and that moment is what counts and breaks WASD recognition.
5. Mindustry starts. Though after it is started active layout is us (default) it does not matter. WASD recognition was broken at step 4

I also found a workaround. To reliably start Mindustry with working WASD movement I had to change startup command to `xkblayout-state set 0; sleep 1; /usr/bin/mindustry`. That explicitly activates first layout ("us") before starting mindustry. And somehow `sleep` is required, workaround does not work without it. Probably because of app switching tracking logic?

**Comment by Anuken** [comment]
@Self-Perfection @ftvkyo Try the very latest commit and let me know if the issue is still there.

**Comment by Self-Perfection** [comment]
@Anuken I've built from db9eb36c8 and it does not have the issue anymore. WASD recognition always works. Thank you!

**Comment by ftvkyo** [comment]
Yep, works perfect. Thank you :3
