### ISSUE TITLE
autoPause bug 

### ISSUE THREAD

**Issue by eSK8er** [Anuken/Mindustry#8340]
**Platform**:  Debian 

**Build**: Server 142

**Issue**: players aren't giving a unit and Server is paused

I have been using autoPause before the update and everything was fine. Since 142 it just stops randomly and I has restarted a few times. There isn't any errors. I have turned autoPause off in config hopefully that will keep it running. 

**Link(s) to mod(s) used**:  Default Server 

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by camelStyleUser** [comment]
[x] i havent read the template

**Comment by L0615T1C5-216AC-9437** [comment]
Have been experiencing something similar in my headless servers. Random server pause after world load which require server restart.

**Comment by L0615T1C5-216AC-9437** [comment]
Was going to make a new issue but remembered this was here so...

**Platform**: Windows 10

**Build**: 142   
Java 18.0.2.1

**Issue**: Server will stay permanently paused randomly after gameover.

**Steps to reproduce**: Join server -> wait for gameover -> bug.

**Link(s) to mod(s) used**: N/A

**Save file**: Client save only, server doesn't allow me to save due to `Not hosting.`.
[clientSavePauseBug.zip](https://github.com/Anuken/Mindustry/files/10902123/clientSavePauseBug.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: N/A, no errors either

**Comment by Anuken** [comment]
So much for #8220 being tested. Reverting.
