### ISSUE TITLE
German help text for impact reactor is too big, widget resize is broken.

### ISSUE THREAD

**Issue by hardliner66** [Anuken/Mindustry#843]
**Platform**: Windows

**Build**: steam build 96

**Issue**: German help text for impact reactor is too big, widget resize is broken. The resize should only effect the help text, and not the whole menu.

**Steps to reproduce**: I made a video, because it's easier to show than to explain: [ui_bug.zip](https://github.com/Anuken/Mindustry/files/3748002/ui_bug.zip)

Edit: Other languages may have the same problem. Haven't testet with other languages.

**Comment by Anuken** [comment]
Even if the text for item names wrapped around in the build menu, the long name of surge alloy would affect other menus with item names as well, making them extremely long and/or hard to use. Instead of changing this one specific behavior, the name of *surge alloy* in German should be changed. Since it's not a real resource, any name that has *something* to do with metal/electricity, and is significantly shorter than the current one will do.

**Comment by hardliner66** [comment]
While changing the name would fix this issue, as soon as another text gets too long the issue will come back. Either way, I don't think the issue should be closed until either resizing is fixed or the text is changed.

**Comment by Anuken** [comment]
> as soon as another text gets too long

I'm saying that *no* item name should get this long, as it will mess with other layouts anyway. I closed this issue since it's translation-specific.
