### ISSUE TITLE
can't change direction like conveyor

### ISSUE THREAD

**Issue by Cong0707** [Anuken/Mindustry#8787]
### Platforms

Windows

### Build

145.1

### Issue

when you place a conveyor on a conveyor with different direction, it can redirect directly
but when you do it on heat redirector or heat router , it won't work
![QQ图片20230703101648](https://github.com/Anuken/Mindustry/assets/49234756/a60c750e-efda-434f-848e-1b4de4d4ba5f)
![QQ图片20230703122746](https://github.com/Anuken/Mindustry/assets/49234756/484b63a9-824a-4cc1-98ea-6476150a7d11)
![QQ图片20230703122818](https://github.com/Anuken/Mindustry/assets/49234756/eb86745e-3702-4ba2-9720-203aec78335a)

### Steps to reproduce

place a heat redirector on a heat redirector with another direction
the same to heat router

### Mods used

no

### Save file

no

### (Crash) logs

no

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by buthed010203** [comment]
This stems from the code below, the blocks are within `BlockGroup.none`. I would argue that blocks not being able to replace themselves when they're in the none group is a bug. Additionally, heat blocks should probably get a group so that they can replace each other.
https://github.com/Anuken/Mindustry/blob/93daa7a5dcc3fac9e5f40c3375e9f57ae4720ff4/core/src/mindustry/world/Block.java#L644-L649
