### ISSUE TITLE
achievement erekir structure mastery 

### ISSUE THREAD

**Issue by JasperChaseTOQ** [Anuken/Mindustry#8851]
### Platforms

Windows

### Build

steam 145.1

### Issue

i built all of the vanilla erekir blocks in two separate sectors (all but one in one and then the fluid pump (or however the erekir version is called in a separate one) and never got the achievement)

im not sure if the issue is that they all have to be in one sector or not but if that is the case then it should specifiy that it has to be in one sector

### Steps to reproduce

build all the vanilla blocks available on erekir (possibly in two seperate sectors)

### Save file

my save file is 38 mb i cant upload past 25 mb 

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment]
Cannot reproduce, placing some Erekir blocks on one sector while having other placed elsewhere triggers the achievement for me.

**Comment by JasperChaseTOQ** [comment]
is it only vanilla blocks or do modded ones count as well? as from what i saw from the code i believe its only vanilla blocks? https://github.com/Anuken/Mindustry/blob/ba9e39d7a4f93270a9d61f33cbb6f0fcdb383710/core/src/mindustry/service/GameService.java#L90C213-L90C213

**Comment by Anuken** [comment]
Only vanilla ones, yes. I tested this in vanilla.

**Comment by JasperChaseTOQ** [comment]
hmmm im not aware of having any mods that affect hidden blocks but ill test this in vanilla later to see if that fixs it ty

**Comment by oubeidong** [comment]
@Anuken @JasperChaseTOQ I unlocked this achievement today and I can provide some information. I started playing the game in v7 and the planet I played first was Erekir instead of Serpulo, and when I unlocked everything about Erekir and built all the blocks, this achievement was not unlocked. But when I started playing Serpulo and unlocked everything in Serpulo, the achievement "Serpulo Structure Mastery" immediately popped up after I built all the blocks of Serpulo. When I restart the game without doing anything, the achievement "Erekir Structure Mastery" pops up immediately. p.s. I have never installed any mods, never enabled the console.
