### ISSUE TITLE
processor interface does not close when disconnected from server

### ISSUE THREAD

**Issue by CodeWizard404** [Anuken/Mindustry#8904]
### Platforms

Android

### Build

145.1

### Issue

Processor interface does not close when disconnected from server

![Screenshot_2023-08-08-06-41-42-462_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/141657099/37fdb945-c26e-40eb-bbfd-761ade6711fc)
![Screenshot_2023-08-08-06-41-32-298_io anuke mindustry](https://github.com/Anuken/Mindustry/assets/141657099/5b301695-0144-4ce7-ac8d-5a2c72b73210)

### Steps to reproduce

1. Connect to any server
2. Open interface processor interface
3. Turn off Internet

### Mods used

None

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by JasonP01** [comment]
@Anuken the "fix" is actually terrible change, the only way to disconnect from a server with the processor menu up is for your internet to disconnect you, or a admin ingame (or server console), and if your in a processor when you disconnect your most likely making logic. All this change does is now make you unable to save your logic if you disconnect due to internet issues!

**Comment by JasonP01** [comment]
> One wonders why someone even bothered to report _and_ thumbs-up this bug, then.

Most likely they do NOT make logic and dont understand how devastating can be to lose your progress in it, its terrible to have your work removed for no reason, its the same thing as your game crashing while your map making before you manage to press save.
