### ISSUE TITLE
game crash when I try to open it

### ISSUE THREAD

**Issue by Maxou-69** [Anuken/Mindustry#8932]
### Platforms

Windows

### Build

145.1/ 2423

### Issue

I want to start the game and a crash file have appear. The game isn't opening

### Steps to reproduce

I don't really know how to reproduce because it's just appear after an update of java

### Mods used

foo client

### (Crash) logs

[hs_err_pid15196.log](https://github.com/Anuken/Mindustry/files/12333839/hs_err_pid15196.log)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by stacktrace-error** [comment]
foo's moment

**Comment by Maxou-69** [comment]
[hs_err_pid21444.log](https://github.com/Anuken/Mindustry/files/12333971/hs_err_pid21444.log)
with jdk 17 same result

**Comment by camelStyleUser** [comment]
`EXCEPTION_ACCESS_VIOLATION` gaming

**Comment by mahdiyadiilavi1** [comment]
Hey, this has happened to me too,
The reason my game crashing was because my gpu was assigned with wrong name and wrong Vram size
I got scammed and bought a fake gpu with 1gigabyte Vram, computer tells me its 2 gigabyte,
I used gpu-z and i was right this gpu was fake. Game memory was being dangerously overflowing and causing unstable behavior:

Glichy textures
Crashes
Hardware failure/BSoD
Damaging game data

You can check your gpu with gpu-z too.

**Comment by mahdiyadiilavi1** [comment]
> Native crash, not something I can fix. Your computer/graphics drivers/something I don't even know is broken.

Youre right, problem is not with game's code.

**Comment by Maxou-69** [comment]
I have found the bug my drivers was not update now it's working nice
