### ISSUE TITLE
problem in mindustry github

### ISSUE THREAD

**Issue by bikename** [Anuken/Mindustry#9806]
### Platforms

Android

### Build

release build 146

### Issue

all community servers and modifications are **gone** and i need a _help_ 
its all.
**_help me_**

### Steps to reproduce

I just entered the game and that's how it was

### Save file

![Screenshot_2024-05-04-11-06-50-281](https://github.com/Anuken/Mindustry/assets/167797832/2ab5c1e3-cba9-4e28-a76a-6d545f912b7f)
![Screenshot_2024-05-04-11-06-33-834](https://github.com/Anuken/Mindustry/assets/167797832/8fd477a4-c961-4939-97c2-64330123edf6)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by bikename** [comment]
wadaheeeeck omagaaaad nowaAaAaAyy

**Comment by Anuken** [comment]
>  I have searched the closed and open issues to make sure that this problem has not already been reported.

No, you have not. This has been reported countless times; it is a problem with your network.

**Comment by bikename** [comment]
💀💀💀 i have 5g but ok

**Comment by camelStyleUser** [comment]
> 💀💀💀 i have 5g but ok

firewalls:

**Comment by Slotterleet** [comment]
ISPs mess you up. Simple.

> 💀💀💀 i have 5g but ok

**Comment by S0meM** [comment]
No, I know what the fix is to this. go to Control Panel\System and Security\Windows Defender Firewall and click on "Allow an app or feature through Windows Defender Firewall.
![Screenshot 2024-05-16 102816](https://github.com/Anuken/Mindustry/assets/148879621/eea29e85-2b0f-42cf-aac3-6230d825d3ab)
Click "Change Settings", then scroll down and find Mindustry, then allow it through both public and private firewalls.
